[project]
name = "Chico"
version = "BETA"
description = "Chico é um utilitário para atividades administrativas do cotidiano escolar."
authors = [
    {name = "Livíssima ", email = "seu.email@exemplo.com"}
]
readme = "README.md"
#requires-python = ">=3.8"
license = {file = "LICENSE"}
keywords = []
classifiers = [
#    "Development Status :: ____ - Beta",
#    "Intended Audience :: ________",
    "Programming Language :: Python :: 3.12",
]

dependencies = [
    "pandas", "selenium", "tabula-py",
    # Adicione outras dependências aqui
]

[project.optional-dependencies]
dev = [
#    "pytest>=7.0.0",
#    "black>=23.0.0",
#    "flake8>=6.0.0",
#    "isort>=5.12.0",
]

[build-system]
requires = []
#build-core = "setuptools.build_meta"

# Configurações para ferramentas adicionais
[tool.black]
#line-length = 88
#target-version = ['py38']

[tool.isort]
#profile = "black"

[tool.pytest.ini_options]
#testpaths = ["tests"]
#python_files = "test_*.py"

## Se estiver usando FastAPI ou similar
#[tool.uvicorn]
#app = "app.inicial:app"
#host = "0.0.0.0"
#port = 8000
#reload = true

# Para empacotamento e distribuição
[tool.setuptools]
#packages = {find = {where = ["app"]}}

[tool.setuptools.package-data]
#"*" = ["*.txt", "*.json", "*.yaml", "*.yml"]