i = {'Dados Pessoais': 'Dados Pessoais'}
i = {'Dados Pessoais': 'CPF', 'coluna_1': '886.823.901-91', 'coluna_2': 'Matrícula Funcional', 'coluna_3': ''}
i = {'Dados Pessoais': 'Nome', 'coluna_1': 'ANA LEMES CHAVES', 'coluna_2': 'Data de Nascimento', 'coluna_3': '26/05/1979'}
i = {'Dados Pessoais': 'Naturalidade', 'coluna_1': 'ITAUÇU', 'coluna_2': 'UF', 'coluna_3': 'GO'}
i = {'Dados Pessoais': 'Nacionalidade', 'coluna_1': 'BRASIL', 'coluna_2': 'Sexo', 'coluna_3': 'Feminino'}
i = {'Dados Pessoais': 'Estado Civil', 'coluna_1': 'Solteiro(a)', 'coluna_2': 'Grau de Instrução', 'coluna_3': 'Educação Superior'}
i = {'Dados Pessoais': 'Pai', 'coluna_1': 'ADINARTE LEANDRO CHAVES DOS REIS', 'coluna_2': '', 'coluna_3': ''}
i = {'Dados Pessoais': 'Mãe', 'coluna_1': 'SUELY FERREIRA LEMES', 'coluna_2': '', 'coluna_3': ''}
i = {'Endereço': 'Endereço'}
i = {'Endereço': 'Logradouro', 'coluna_1': 'RUA 01 QD. K LT. 02'}
i = {'Endereço': 'Bairro', 'coluna_1': 'AGUA BRANCA', 'coluna_2': 'Complemento', 'coluna_3': '', 'coluna_4': 'Cep', 'coluna_5': '74723-180'}
i = {'Endereço': 'Município', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO', 'coluna_4': '', 'coluna_5': ''}
i = {'Endereço': 'E-mail', 'coluna_1': 'multihonest@hotmail.com', 'coluna_2': 'Telefone', 'coluna_3': '6299052433', 'coluna_4': 'Tipo Moradia', 'coluna_5': 'Própria'}
i = {'Endereço': ''}
i = {'Endereço': 'Documento'}
i = {'Endereço': 'Identidade', 'coluna_1': '4129716', 'coluna_2': 'Orgão Expedidor', 'coluna_3': 'Outros Emissores', 'coluna_4': 'Data Expedição', 'coluna_5': '26/05/1979', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'Título', 'coluna_1': '038952361007', 'coluna_2': 'Zona', 'coluna_3': '135', 'coluna_4': 'Seção', 'coluna_5': '294', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'C.Militar Número', 'coluna_1': '', 'coluna_2': 'C.M. Região', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Endereço': 'NCH Número', 'coluna_1': '03706476749', 'coluna_2': 'CNH Validade', 'coluna_3': '17/10/2025', 'coluna_4': 'CNH Dt. Exp', 'coluna_5': '14/08/2020', 'coluna_6': 'CNH Cart.', 'coluna_7': 'b'}
i = {'Endereço': 'IPASGO', 'coluna_1': '400155900', 'coluna_2': 'PIS/PASEP', 'coluna_3': '19002993393', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Vínculos': 'Vínculos'}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '', 'coluna_1': '22/12/2004', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'Professor IV', 'coluna_1': '22/12/2004', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': 'PROFESSOR DE 2ª FASE OU ENSINO MÉDIO', 'coluna_1': '01/01/2026', 'coluna_2': '31/12/2026'}
i = {'Vínculos': 'COORDENADOR DE ÁREA - CEPI', 'coluna_1': '01/01/2026', 'coluna_2': '31/12/2026'}
i = {'Dados Pessoais': 'Dados Pessoais'}
i = {'Dados Pessoais': 'CPF', 'coluna_1': '340.995.731-68', 'coluna_2': 'Matrícula Funcional', 'coluna_3': ''}
i = {'Dados Pessoais': 'Nome', 'coluna_1': 'ANDREA DO CARMO PEREIRA ALMEIDA', 'coluna_2': 'Data de Nascimento', 'coluna_3': '09/04/1966'}
i = {'Dados Pessoais': 'Naturalidade', 'coluna_1': 'JUIZ DE FORA', 'coluna_2': 'UF', 'coluna_3': 'MG'}
i = {'Dados Pessoais': 'Nacionalidade', 'coluna_1': 'BRASIL', 'coluna_2': 'Sexo', 'coluna_3': 'Feminino'}
i = {'Dados Pessoais': 'Estado Civil', 'coluna_1': 'Casado(a)', 'coluna_2': 'Grau de Instrução', 'coluna_3': 'Educação Superior'}
i = {'Dados Pessoais': 'Pai', 'coluna_1': 'ARMANDO PEREIRA MARTINS', 'coluna_2': '', 'coluna_3': ''}
i = {'Dados Pessoais': 'Mãe', 'coluna_1': 'JANDIRA CARMO RIBEIRO', 'coluna_2': '', 'coluna_3': ''}
i = {'Endereço': 'Endereço'}
i = {'Endereço': 'Logradouro', 'coluna_1': 'RUA PERIMETRAL'}
i = {'Endereço': 'Bairro', 'coluna_1': 'CONJUNTO RIVIERA', 'coluna_2': 'Complemento', 'coluna_3': 'QD. 01, LT17', 'coluna_4': 'Cep', 'coluna_5': '74730-015'}
i = {'Endereço': 'Município', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO', 'coluna_4': '', 'coluna_5': ''}
i = {'Endereço': 'E-mail', 'coluna_1': 'andreadcpa@hotmail.com', 'coluna_2': 'Telefone', 'coluna_3': '6232840084', 'coluna_4': 'Tipo Moradia', 'coluna_5': 'Própria'}
i = {'Endereço': ''}
i = {'Endereço': 'Documento'}
i = {'Endereço': 'Identidade', 'coluna_1': '20987736646085', 'coluna_2': 'Orgão Expedidor', 'coluna_3': 'SSP', 'coluna_4': 'Data Expedição', 'coluna_5': '09/01/1987', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'Título', 'coluna_1': '296432010/15', 'coluna_2': 'Zona', 'coluna_3': '094', 'coluna_4': 'Seção', 'coluna_5': '0030', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'C.Militar Número', 'coluna_1': '', 'coluna_2': 'C.M. Região', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Endereço': 'NCH Número', 'coluna_1': '', 'coluna_2': 'CNH Validade', 'coluna_3': '', 'coluna_4': 'CNH Dt. Exp', 'coluna_5': '', 'coluna_6': 'CNH Cart.', 'coluna_7': ''}
i = {'Endereço': 'IPASGO', 'coluna_1': '', 'coluna_2': 'PIS/PASEP', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Vínculos': 'Vínculos'}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '54222078', 'coluna_1': '08/03/1993', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'Professor IV', 'coluna_1': '08/03/1993', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': 'COORDENADOR PEDAGÓGICO CEPI', 'coluna_1': '01/01/2026', 'coluna_2': '31/12/2026'}
i = {'Dados Pessoais': 'Dados Pessoais'}
i = {'Dados Pessoais': 'CPF', 'coluna_1': '454.227.961-87', 'coluna_2': 'Matrícula Funcional', 'coluna_3': ''}
i = {'Dados Pessoais': 'Nome', 'coluna_1': 'AUCILEIA FERNANDES DE CARVALHO ROCHA', 'coluna_2': 'Data de Nascimento', 'coluna_3': '02/08/1969'}
i = {'Dados Pessoais': 'Naturalidade', 'coluna_1': 'GURUPI', 'coluna_2': 'UF', 'coluna_3': 'TO'}
i = {'Dados Pessoais': 'Nacionalidade', 'coluna_1': 'BRASIL', 'coluna_2': 'Sexo', 'coluna_3': 'Feminino'}
i = {'Dados Pessoais': 'Estado Civil', 'coluna_1': 'Casado(a)', 'coluna_2': 'Grau de Instrução', 'coluna_3': 'Educação Superior'}
i = {'Dados Pessoais': 'Pai', 'coluna_1': 'ALDERICO CARVALHO DE SOUZA', 'coluna_2': '', 'coluna_3': ''}
i = {'Dados Pessoais': 'Mãe', 'coluna_1': 'LUZIA FERNANDES DE CARVALHO', 'coluna_2': '', 'coluna_3': ''}
i = {'Endereço': 'Endereço'}
i = {'Endereço': 'Logradouro', 'coluna_1': 'R X15'}
i = {'Endereço': 'Bairro', 'coluna_1': 'JD BRASIL', 'coluna_2': 'Complemento', 'coluna_3': 'Q X24 LT 01', 'coluna_4': 'Cep', 'coluna_5': '74730-470'}
i = {'Endereço': 'Município', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO', 'coluna_4': '', 'coluna_5': ''}
i = {'Endereço': 'E-mail', 'coluna_1': 'aucileia.carvalho@seduc.go.gov.br', 'coluna_2': 'Telefone', 'coluna_3': '6232843812', 'coluna_4': 'Tipo Moradia', 'coluna_5': 'Própria'}
i = {'Endereço': ''}
i = {'Endereço': 'Documento'}
i = {'Endereço': 'Identidade', 'coluna_1': '1871784', 'coluna_2': 'Orgão Expedidor', 'coluna_3': 'SSP', 'coluna_4': 'Data Expedição', 'coluna_5': '17/01/1986', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'Título', 'coluna_1': '0027221611007', 'coluna_2': 'Zona', 'coluna_3': '135', 'coluna_4': 'Seção', 'coluna_5': '24', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'C.Militar Número', 'coluna_1': '', 'coluna_2': 'C.M. Região', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Endereço': 'NCH Número', 'coluna_1': '', 'coluna_2': 'CNH Validade', 'coluna_3': '', 'coluna_4': 'CNH Dt. Exp', 'coluna_5': '', 'coluna_6': 'CNH Cart.', 'coluna_7': ''}
i = {'Endereço': 'IPASGO', 'coluna_1': '', 'coluna_2': 'PIS/PASEP', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Vínculos': 'Vínculos'}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '65011681', 'coluna_1': '10/08/1999', 'coluna_2': '31/12/2014'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'Agente Administrativo Educacional Técnico (T)', 'coluna_1': '10/08/1999', 'coluna_2': '31/12/2014'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': '-', 'coluna_1': '-', 'coluna_2': '-'}
i = {'Vínculos': ''}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '', 'coluna_1': '16/08/1999', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'Agente Administrativo Educacional Apoio (A)', 'coluna_1': '16/08/1999', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': 'AUXILIAR PEDAGÓGICO DISCIPLINAR', 'coluna_1': '01/01/2026', 'coluna_2': '31/12/2026'}
i = {'Dados Pessoais': 'Dados Pessoais'}
i = {'Dados Pessoais': 'CPF', 'coluna_1': '363.967.021-34', 'coluna_2': 'Matrícula Funcional', 'coluna_3': ''}
i = {'Dados Pessoais': 'Nome', 'coluna_1': 'DEIJA DOS SANTOS TAVARES', 'coluna_2': 'Data de Nascimento', 'coluna_3': '27/11/1959'}
i = {'Dados Pessoais': 'Naturalidade', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO'}
i = {'Dados Pessoais': 'Nacionalidade', 'coluna_1': 'BRASIL', 'coluna_2': 'Sexo', 'coluna_3': 'Feminino'}
i = {'Dados Pessoais': 'Estado Civil', 'coluna_1': 'Casado(a)', 'coluna_2': 'Grau de Instrução', 'coluna_3': 'Ensino Médio'}
i = {'Dados Pessoais': 'Pai', 'coluna_1': 'ARNALDO DOS SANTOS', 'coluna_2': '', 'coluna_3': ''}
i = {'Dados Pessoais': 'Mãe', 'coluna_1': 'NILZA PEREIRA DOS SANTOS', 'coluna_2': '', 'coluna_3': ''}
i = {'Endereço': 'Endereço'}
i = {'Endereço': 'Logradouro', 'coluna_1': 'RUA HUMAITA'}
i = {'Endereço': 'Bairro', 'coluna_1': 'JARDIM NOVO MUNDO', 'coluna_2': 'Complemento', 'coluna_3': 'QUADRA 10 LOTE 20', 'coluna_4': 'Cep', 'coluna_5': '74715-190'}
i = {'Endereço': 'Município', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO', 'coluna_4': '', 'coluna_5': ''}
i = {'Endereço': 'E-mail', 'coluna_1': '', 'coluna_2': 'Telefone', 'coluna_3': '6232843510', 'coluna_4': 'Tipo Moradia', 'coluna_5': 'Cedida'}
i = {'Endereço': ''}
i = {'Endereço': 'Documento'}
i = {'Endereço': 'Identidade', 'coluna_1': '1623582 2ª VIA', 'coluna_2': 'Orgão Expedidor', 'coluna_3': 'SSP', 'coluna_4': 'Data Expedição', 'coluna_5': '29/11/2010', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'Título', 'coluna_1': '019645931074', 'coluna_2': 'Zona', 'coluna_3': '135', 'coluna_4': 'Seção', 'coluna_5': '0047', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'C.Militar Número', 'coluna_1': '', 'coluna_2': 'C.M. Região', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Endereço': 'NCH Número', 'coluna_1': '', 'coluna_2': 'CNH Validade', 'coluna_3': '', 'coluna_4': 'CNH Dt. Exp', 'coluna_5': '', 'coluna_6': 'CNH Cart.', 'coluna_7': ''}
i = {'Endereço': 'IPASGO', 'coluna_1': '', 'coluna_2': 'PIS/PASEP', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Vínculos': 'Vínculos'}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '', 'coluna_1': '28/08/1999', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'Agente Administrativo Educacional Apoio (A)', 'coluna_1': '28/08/1999', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': 'READAPTAÇÃO ADMINISTRATIVO', 'coluna_1': '02/01/2026', 'coluna_2': '31/12/2026'}
i = {'Dados Pessoais': 'Dados Pessoais'}
i = {'Dados Pessoais': 'CPF', 'coluna_1': '532.274.681-15', 'coluna_2': 'Matrícula Funcional', 'coluna_3': ''}
i = {'Dados Pessoais': 'Nome', 'coluna_1': 'DENISE LUZIA DE CARVALHO', 'coluna_2': 'Data de Nascimento', 'coluna_3': '13/12/1970'}
i = {'Dados Pessoais': 'Naturalidade', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO'}
i = {'Dados Pessoais': 'Nacionalidade', 'coluna_1': 'BRASIL', 'coluna_2': 'Sexo', 'coluna_3': 'Feminino'}
i = {'Dados Pessoais': 'Estado Civil', 'coluna_1': 'Divorciado(a)', 'coluna_2': 'Grau de Instrução', 'coluna_3': 'Educação Superior'}
i = {'Dados Pessoais': 'Pai', 'coluna_1': 'MOISÉS CARVALHO BARROS', 'coluna_2': '', 'coluna_3': ''}
i = {'Dados Pessoais': 'Mãe', 'coluna_1': 'MARIA JOSE CARVALHO', 'coluna_2': '', 'coluna_3': ''}
i = {'Endereço': 'Endereço'}
i = {'Endereço': 'Logradouro', 'coluna_1': 'RUA 6A'}
i = {'Endereço': 'Bairro', 'coluna_1': 'AGUA BRANCA', 'coluna_2': 'Complemento', 'coluna_3': 'Q O L 3', 'coluna_4': 'Cep', 'coluna_5': '74723-350'}
i = {'Endereço': 'Município', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO', 'coluna_4': '', 'coluna_5': ''}
i = {'Endereço': 'E-mail', 'coluna_1': 'denisecrisare@hotmail.com', 'coluna_2': 'Telefone', 'coluna_3': '6292180099', 'coluna_4': 'Tipo Moradia', 'coluna_5': 'Própria'}
i = {'Endereço': ''}
i = {'Endereço': 'Documento'}
i = {'Endereço': 'Identidade', 'coluna_1': '1976406', 'coluna_2': 'Orgão Expedidor', 'coluna_3': 'SSP', 'coluna_4': 'Data Expedição', 'coluna_5': '01/09/1987', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'Título', 'coluna_1': '26044591058', 'coluna_2': 'Zona', 'coluna_3': '126', 'coluna_4': 'Seção', 'coluna_5': '296', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'C.Militar Número', 'coluna_1': '', 'coluna_2': 'C.M. Região', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Endereço': 'NCH Número', 'coluna_1': '', 'coluna_2': 'CNH Validade', 'coluna_3': '', 'coluna_4': 'CNH Dt. Exp', 'coluna_5': '', 'coluna_6': 'CNH Cart.', 'coluna_7': ''}
i = {'Endereço': 'IPASGO', 'coluna_1': '', 'coluna_2': 'PIS/PASEP', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Vínculos': 'Vínculos'}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '50742156', 'coluna_1': '20/02/2004', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'Professor III', 'coluna_1': '01/01/2011', 'coluna_2': '31/12/2014'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': '-', 'coluna_1': '-', 'coluna_2': '-'}
i = {'Vínculos': 'Professor IV', 'coluna_1': '20/02/2004', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': 'PROFESSOR DE 2ª FASE OU ENSINO MÉDIO', 'coluna_1': '01/01/2026', 'coluna_2': '31/12/2026'}
i = {'Dados Pessoais': 'Dados Pessoais'}
i = {'Dados Pessoais': 'CPF', 'coluna_1': '843.957.611-00', 'coluna_2': 'Matrícula Funcional', 'coluna_3': ''}
i = {'Dados Pessoais': 'Nome', 'coluna_1': 'DINA DA LUZ DOS SANTOS', 'coluna_2': 'Data de Nascimento', 'coluna_3': '25/06/1976'}
i = {'Dados Pessoais': 'Naturalidade', 'coluna_1': '', 'coluna_2': 'UF', 'coluna_3': ''}
i = {'Dados Pessoais': 'Nacionalidade', 'coluna_1': '', 'coluna_2': 'Sexo', 'coluna_3': 'Feminino'}
i = {'Dados Pessoais': 'Estado Civil', 'coluna_1': 'Não informado', 'coluna_2': 'Grau de Instrução', 'coluna_3': ''}
i = {'Dados Pessoais': 'Pai', 'coluna_1': '', 'coluna_2': '', 'coluna_3': ''}
i = {'Dados Pessoais': 'Mãe', 'coluna_1': 'MARIA DA LUZ DOS SANTOS', 'coluna_2': '', 'coluna_3': ''}
i = {'Endereço': 'Endereço'}
i = {'Endereço': 'Logradouro', 'coluna_1': ''}
i = {'Endereço': 'Bairro', 'coluna_1': '', 'coluna_2': 'Complemento', 'coluna_3': '', 'coluna_4': 'Cep', 'coluna_5': ''}
i = {'Endereço': 'Município', 'coluna_1': '', 'coluna_2': 'UF', 'coluna_3': '', 'coluna_4': '', 'coluna_5': ''}
i = {'Endereço': 'E-mail', 'coluna_1': '', 'coluna_2': 'Telefone', 'coluna_3': '', 'coluna_4': 'Tipo Moradia', 'coluna_5': ''}
i = {'Endereço': ''}
i = {'Endereço': 'Documento'}
i = {'Endereço': 'Identidade', 'coluna_1': '', 'coluna_2': 'Orgão Expedidor', 'coluna_3': '', 'coluna_4': 'Data Expedição', 'coluna_5': '', 'coluna_6': 'UF', 'coluna_7': ''}
i = {'Endereço': 'Título', 'coluna_1': '', 'coluna_2': 'Zona', 'coluna_3': '', 'coluna_4': 'Seção', 'coluna_5': '', 'coluna_6': 'UF', 'coluna_7': ''}
i = {'Endereço': 'C.Militar Número', 'coluna_1': '', 'coluna_2': 'C.M. Região', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Endereço': 'NCH Número', 'coluna_1': '', 'coluna_2': 'CNH Validade', 'coluna_3': '', 'coluna_4': 'CNH Dt. Exp', 'coluna_5': '', 'coluna_6': 'CNH Cart.', 'coluna_7': ''}
i = {'Endereço': 'IPASGO', 'coluna_1': '', 'coluna_2': 'PIS/PASEP', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Vínculos': 'Vínculos'}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '', 'coluna_1': '01/09/2025', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'C.Temporário - Apoio Administrativo - Nível Fundamental - SEDUC', 'coluna_1': '01/09/2025', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': 'EXECUTOR DE SERVIÇOS AUXILIARES', 'coluna_1': '01/01/2026', 'coluna_2': '31/12/2026'}
i = {'Dados Pessoais': 'Dados Pessoais'}
i = {'Dados Pessoais': 'CPF', 'coluna_1': '292.320.308-96', 'coluna_2': 'Matrícula Funcional', 'coluna_3': ''}
i = {'Dados Pessoais': 'Nome', 'coluna_1': 'ELISRENNE RENOVATO DOS SANTOS', 'coluna_2': 'Data de Nascimento', 'coluna_3': '01/07/1977'}
i = {'Dados Pessoais': 'Naturalidade', 'coluna_1': 'PORANGATU', 'coluna_2': 'UF', 'coluna_3': 'GO'}
i = {'Dados Pessoais': 'Nacionalidade', 'coluna_1': 'BRASIL', 'coluna_2': 'Sexo', 'coluna_3': 'Feminino'}
i = {'Dados Pessoais': 'Estado Civil', 'coluna_1': 'Solteiro(a)', 'coluna_2': 'Grau de Instrução', 'coluna_3': 'Educação Superior'}
i = {'Dados Pessoais': 'Pai', 'coluna_1': 'JOSE HAHOR RENOVATO DOS SANTOS', 'coluna_2': '', 'coluna_3': ''}
i = {'Dados Pessoais': 'Mãe', 'coluna_1': 'ELIZABETE CORREA DOS SANTOS', 'coluna_2': '', 'coluna_3': ''}
i = {'Endereço': 'Endereço'}
i = {'Endereço': 'Logradouro', 'coluna_1': 'RUA S 5'}
i = {'Endereço': 'Bairro', 'coluna_1': 'BELA VISTA', 'coluna_2': 'Complemento', 'coluna_3': 'APT 703', 'coluna_4': 'Cep', 'coluna_5': '74823-460'}
i = {'Endereço': 'Município', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO', 'coluna_4': '', 'coluna_5': ''}
i = {'Endereço': 'E-mail', 'coluna_1': 'elisrennerenovato@gmail.com', 'coluna_2': 'Telefone', 'coluna_3': '6232843041', 'coluna_4': 'Tipo Moradia', 'coluna_5': 'Alugada'}
i = {'Endereço': ''}
i = {'Endereço': 'Documento'}
i = {'Endereço': 'Identidade', 'coluna_1': '3574527', 'coluna_2': 'Orgão Expedidor', 'coluna_3': 'SSP', 'coluna_4': 'Data Expedição', 'coluna_5': '23/02/1994', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'Título', 'coluna_1': '38872901007', 'coluna_2': 'Zona', 'coluna_3': '55', 'coluna_4': 'Seção', 'coluna_5': '29', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'C.Militar Número', 'coluna_1': '', 'coluna_2': 'C.M. Região', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Endereço': 'NCH Número', 'coluna_1': '', 'coluna_2': 'CNH Validade', 'coluna_3': '', 'coluna_4': 'CNH Dt. Exp', 'coluna_5': '', 'coluna_6': 'CNH Cart.', 'coluna_7': ''}
i = {'Endereço': 'IPASGO', 'coluna_1': '', 'coluna_2': 'PIS/PASEP', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Vínculos': 'Vínculos'}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '', 'coluna_1': '01/11/2006', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'Professor IV', 'coluna_1': '01/11/2006', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': 'PROFESSOR DE 2ª FASE OU ENSINO MÉDIO', 'coluna_1': '01/01/2026', 'coluna_2': '31/12/2026'}
i = {'Dados Pessoais': 'Dados Pessoais'}
i = {'Dados Pessoais': 'CPF', 'coluna_1': '663.473.352-04', 'coluna_2': 'Matrícula Funcional', 'coluna_3': ''}
i = {'Dados Pessoais': 'Nome', 'coluna_1': 'ERINALVA CLEMENTINO FERREIRA NARCISO', 'coluna_2': 'Data de Nascimento', 'coluna_3': '26/04/1976'}
i = {'Dados Pessoais': 'Naturalidade', 'coluna_1': 'ALTAMIRA', 'coluna_2': 'UF', 'coluna_3': 'PA'}
i = {'Dados Pessoais': 'Nacionalidade', 'coluna_1': 'BRASIL', 'coluna_2': 'Sexo', 'coluna_3': 'Feminino'}
i = {'Dados Pessoais': 'Estado Civil', 'coluna_1': 'Casado(a)', 'coluna_2': 'Grau de Instrução', 'coluna_3': 'Ensino Médio'}
i = {'Dados Pessoais': 'Pai', 'coluna_1': '', 'coluna_2': '', 'coluna_3': ''}
i = {'Dados Pessoais': 'Mãe', 'coluna_1': 'JOSEFA BATISTA FERREIRA', 'coluna_2': '', 'coluna_3': ''}
i = {'Endereço': 'Endereço'}
i = {'Endereço': 'Logradouro', 'coluna_1': 'rua x10 qd x12 lt 02'}
i = {'Endereço': 'Bairro', 'coluna_1': 'jardim brasil', 'coluna_2': 'Complemento', 'coluna_3': '', 'coluna_4': 'Cep', 'coluna_5': '74730-420'}
i = {'Endereço': 'Município', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO', 'coluna_4': '', 'coluna_5': ''}
i = {'Endereço': 'E-mail', 'coluna_1': 'nanaferreirah@hotmail.com', 'coluna_2': 'Telefone', 'coluna_3': '62984318432', 'coluna_4': 'Tipo Moradia', 'coluna_5': 'Própria'}
i = {'Endereço': ''}
i = {'Endereço': 'Documento'}
i = {'Endereço': 'Identidade', 'coluna_1': '7444264', 'coluna_2': 'Orgão Expedidor', 'coluna_3': 'SSP', 'coluna_4': 'Data Expedição', 'coluna_5': '13/03/2019', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'Título', 'coluna_1': '032027811384', 'coluna_2': 'Zona', 'coluna_3': '135', 'coluna_4': 'Seção', 'coluna_5': '016', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'C.Militar Número', 'coluna_1': '', 'coluna_2': 'C.M. Região', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Endereço': 'NCH Número', 'coluna_1': '', 'coluna_2': 'CNH Validade', 'coluna_3': '', 'coluna_4': 'CNH Dt. Exp', 'coluna_5': '', 'coluna_6': 'CNH Cart.', 'coluna_7': ''}
i = {'Endereço': 'IPASGO', 'coluna_1': '', 'coluna_2': 'PIS/PASEP', 'coluna_3': '14047526319', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Vínculos': 'Vínculos'}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '', 'coluna_1': '27/04/2017', 'coluna_2': '29/02/2020'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'C.Temporário - Apoio Administrativo - Nível Fundamental - SEDUC', 'coluna_1': '27/04/2017', 'coluna_2': '29/02/2020'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': '-', 'coluna_1': '-', 'coluna_2': '-'}
i = {'Vínculos': ''}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '', 'coluna_1': '01/02/2022', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'C.Temporário - Apoio Administrativo - Nível Fundamental - SEDUC', 'coluna_1': '01/02/2022', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': 'EXECUTOR DE SERVIÇOS AUXILIARES', 'coluna_1': '01/01/2026', 'coluna_2': '31/12/2026'}
i = {'Dados Pessoais': 'Dados Pessoais'}
i = {'Dados Pessoais': 'CPF', 'coluna_1': '891.206.551-34', 'coluna_2': 'Matrícula Funcional', 'coluna_3': ''}
i = {'Dados Pessoais': 'Nome', 'coluna_1': 'IGOR TARAPANOFF FILHO', 'coluna_2': 'Data de Nascimento', 'coluna_3': '29/09/1979'}
i = {'Dados Pessoais': 'Naturalidade', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO'}
i = {'Dados Pessoais': 'Nacionalidade', 'coluna_1': 'BRASIL', 'coluna_2': 'Sexo', 'coluna_3': 'Masculino'}
i = {'Dados Pessoais': 'Estado Civil', 'coluna_1': 'Solteiro(a)', 'coluna_2': 'Grau de Instrução', 'coluna_3': 'Educação Superior'}
i = {'Dados Pessoais': 'Pai', 'coluna_1': 'IGOR TARAPANOFF', 'coluna_2': '', 'coluna_3': ''}
i = {'Dados Pessoais': 'Mãe', 'coluna_1': "ACELY MIRZA D'ANDREA TARAPANOFF", 'coluna_2': '', 'coluna_3': ''}
i = {'Endereço': 'Endereço'}
i = {'Endereço': 'Logradouro', 'coluna_1': 'RUA J6 QD. 15 LT. 03 Nº 387'}
i = {'Endereço': 'Bairro', 'coluna_1': 'SETOR JAÓ', 'coluna_2': 'Complemento', 'coluna_3': '', 'coluna_4': 'Cep', 'coluna_5': '74673-180'}
i = {'Endereço': 'Município', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO', 'coluna_4': '', 'coluna_5': ''}
i = {'Endereço': 'E-mail', 'coluna_1': 'igortarapanoff2979@gmail.com', 'coluna_2': 'Telefone', 'coluna_3': '6285787114', 'coluna_4': 'Tipo Moradia', 'coluna_5': 'Própria'}
i = {'Endereço': ''}
i = {'Endereço': 'Documento'}
i = {'Endereço': 'Identidade', 'coluna_1': '2181000 2. A VIA', 'coluna_2': 'Orgão Expedidor', 'coluna_3': 'Outros Emissores', 'coluna_4': 'Data Expedição', 'coluna_5': '27/01/1997', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'Título', 'coluna_1': '39340351007', 'coluna_2': 'Zona', 'coluna_3': '146', 'coluna_4': 'Seção', 'coluna_5': '116', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'C.Militar Número', 'coluna_1': '', 'coluna_2': 'C.M. Região', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Endereço': 'NCH Número', 'coluna_1': '01274549462', 'coluna_2': 'CNH Validade', 'coluna_3': '17/09/2023', 'coluna_4': 'CNH Dt. Exp', 'coluna_5': '19/09/2018', 'coluna_6': 'CNH Cart.', 'coluna_7': 'B'}
i = {'Endereço': 'IPASGO', 'coluna_1': '', 'coluna_2': 'PIS/PASEP', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Vínculos': 'Vínculos'}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '', 'coluna_1': '21/02/2004', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'Professor IV', 'coluna_1': '21/02/2004', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': 'PROFESSOR DE 2ª FASE OU ENSINO MÉDIO', 'coluna_1': '01/01/2026', 'coluna_2': '31/12/2026'}
i = {'Dados Pessoais': 'Dados Pessoais'}
i = {'Dados Pessoais': 'CPF', 'coluna_1': '576.580.301-63', 'coluna_2': 'Matrícula Funcional', 'coluna_3': ''}
i = {'Dados Pessoais': 'Nome', 'coluna_1': 'ISMENE FERNANDES DA SILVA', 'coluna_2': 'Data de Nascimento', 'coluna_3': '24/05/1970'}
i = {'Dados Pessoais': 'Naturalidade', 'coluna_1': 'CATALÃO', 'coluna_2': 'UF', 'coluna_3': 'GO'}
i = {'Dados Pessoais': 'Nacionalidade', 'coluna_1': 'BRASIL', 'coluna_2': 'Sexo', 'coluna_3': 'Feminino'}
i = {'Dados Pessoais': 'Estado Civil', 'coluna_1': 'Solteiro(a)', 'coluna_2': 'Grau de Instrução', 'coluna_3': 'Educação Superior'}
i = {'Dados Pessoais': 'Pai', 'coluna_1': 'JESY FRANCISCO DA SILVA', 'coluna_2': '', 'coluna_3': ''}
i = {'Dados Pessoais': 'Mãe', 'coluna_1': 'MARIA DOS ANJOS SILVA', 'coluna_2': '', 'coluna_3': ''}
i = {'Endereço': 'Endereço'}
i = {'Endereço': 'Logradouro', 'coluna_1': 'RUA ANTONIO TORQUATO'}
i = {'Endereço': 'Bairro', 'coluna_1': 'CENTRO', 'coluna_2': 'Complemento', 'coluna_3': 'casa', 'coluna_4': 'Cep', 'coluna_5': '75715-000'}
i = {'Endereço': 'Município', 'coluna_1': 'OUVIDOR', 'coluna_2': 'UF', 'coluna_3': 'GO', 'coluna_4': '', 'coluna_5': ''}
i = {'Endereço': 'E-mail', 'coluna_1': 'ismenefsilva@gmail.com', 'coluna_2': 'Telefone', 'coluna_3': '64992949990', 'coluna_4': 'Tipo Moradia', 'coluna_5': 'Alugada'}
i = {'Endereço': ''}
i = {'Endereço': 'Documento'}
i = {'Endereço': 'Identidade', 'coluna_1': '3275910-3498352', 'coluna_2': 'Orgão Expedidor', 'coluna_3': 'SSP', 'coluna_4': 'Data Expedição', 'coluna_5': '28/11/1991', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'Título', 'coluna_1': '219024210 90', 'coluna_2': 'Zona', 'coluna_3': '8', 'coluna_4': 'Seção', 'coluna_5': '2', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'C.Militar Número', 'coluna_1': '', 'coluna_2': 'C.M. Região', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Endereço': 'NCH Número', 'coluna_1': '', 'coluna_2': 'CNH Validade', 'coluna_3': '', 'coluna_4': 'CNH Dt. Exp', 'coluna_5': '', 'coluna_6': 'CNH Cart.', 'coluna_7': ''}
i = {'Endereço': 'IPASGO', 'coluna_1': '', 'coluna_2': 'PIS/PASEP', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Vínculos': 'Vínculos'}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '', 'coluna_1': '03/08/1999', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'Professor IV', 'coluna_1': '03/08/1999', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': 'PROFESSOR DE 2ª FASE OU ENSINO MÉDIO', 'coluna_1': '05/01/2026', 'coluna_2': '31/12/2026'}
i = {'Dados Pessoais': 'Dados Pessoais'}
i = {'Dados Pessoais': 'CPF', 'coluna_1': '872.603.951-68', 'coluna_2': 'Matrícula Funcional', 'coluna_3': '19360'}
i = {'Dados Pessoais': 'Nome', 'coluna_1': 'JAIDAN GUALBERTO DA SILVA OLIVEIRA', 'coluna_2': 'Data de Nascimento', 'coluna_3': '20/01/1975'}
i = {'Dados Pessoais': 'Naturalidade', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO'}
i = {'Dados Pessoais': 'Nacionalidade', 'coluna_1': 'BRASIL', 'coluna_2': 'Sexo', 'coluna_3': 'Feminino'}
i = {'Dados Pessoais': 'Estado Civil', 'coluna_1': 'Casado(a)', 'coluna_2': 'Grau de Instrução', 'coluna_3': 'Ensino Médio'}
i = {'Dados Pessoais': 'Pai', 'coluna_1': 'SEBASTIÃO BISPO DA SILVA', 'coluna_2': '', 'coluna_3': ''}
i = {'Dados Pessoais': 'Mãe', 'coluna_1': 'MARIA DA GLORIA GUALBERTO DA SILVA', 'coluna_2': '', 'coluna_3': ''}
i = {'Endereço': 'Endereço'}
i = {'Endereço': 'Logradouro', 'coluna_1': 'RUA LONDRINA, QD.79B, LT. 01'}
i = {'Endereço': 'Bairro', 'coluna_1': 'JARDIM NOVO MUNDO', 'coluna_2': 'Complemento', 'coluna_3': '', 'coluna_4': 'Cep', 'coluna_5': '74715-280'}
i = {'Endereço': 'Município', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO', 'coluna_4': '', 'coluna_5': ''}
i = {'Endereço': 'E-mail', 'coluna_1': '', 'coluna_2': 'Telefone', 'coluna_3': '6284365839', 'coluna_4': 'Tipo Moradia', 'coluna_5': 'Cedida'}
i = {'Endereço': ''}
i = {'Endereço': 'Documento'}
i = {'Endereço': 'Identidade', 'coluna_1': '3218825', 'coluna_2': 'Orgão Expedidor', 'coluna_3': 'Outros Emissores', 'coluna_4': 'Data Expedição', 'coluna_5': '21/07/1997', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'Título', 'coluna_1': '329171411074', 'coluna_2': 'Zona', 'coluna_3': '135', 'coluna_4': 'Seção', 'coluna_5': '053', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'C.Militar Número', 'coluna_1': '', 'coluna_2': 'C.M. Região', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Endereço': 'NCH Número', 'coluna_1': '', 'coluna_2': 'CNH Validade', 'coluna_3': '', 'coluna_4': 'CNH Dt. Exp', 'coluna_5': '', 'coluna_6': 'CNH Cart.', 'coluna_7': ''}
i = {'Endereço': 'IPASGO', 'coluna_1': '2928973', 'coluna_2': 'PIS/PASEP', 'coluna_3': '190042879.25', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Vínculos': 'Vínculos'}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '', 'coluna_1': '15/08/1999', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'Agente Administrativo Educacional Apoio (A)', 'coluna_1': '15/08/1999', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': 'AUXILIAR DE ALIMENTAÇAO', 'coluna_1': '01/01/2026', 'coluna_2': '31/12/2026'}
i = {'Dados Pessoais': 'Dados Pessoais'}
i = {'Dados Pessoais': 'CPF', 'coluna_1': '989.228.661-87', 'coluna_2': 'Matrícula Funcional', 'coluna_3': ''}
i = {'Dados Pessoais': 'Nome', 'coluna_1': 'JOSE CARLOS NERES MOREIRA', 'coluna_2': 'Data de Nascimento', 'coluna_3': '01/04/1984'}
i = {'Dados Pessoais': 'Naturalidade', 'coluna_1': 'CAMPOS BELOS', 'coluna_2': 'UF', 'coluna_3': 'GO'}
i = {'Dados Pessoais': 'Nacionalidade', 'coluna_1': 'BRASIL', 'coluna_2': 'Sexo', 'coluna_3': 'Masculino'}
i = {'Dados Pessoais': 'Estado Civil', 'coluna_1': 'Solteiro(a)', 'coluna_2': 'Grau de Instrução', 'coluna_3': 'Educação Superior'}
i = {'Dados Pessoais': 'Pai', 'coluna_1': 'JOSÉ MOREIRA NETO', 'coluna_2': '', 'coluna_3': ''}
i = {'Dados Pessoais': 'Mãe', 'coluna_1': 'NERCINA NERES MOREIRA', 'coluna_2': '', 'coluna_3': ''}
i = {'Endereço': 'Endereço'}
i = {'Endereço': 'Logradouro', 'coluna_1': 'AVENIDA MANCHESTER'}
i = {'Endereço': 'Bairro', 'coluna_1': 'CENTRO', 'coluna_2': 'Complemento', 'coluna_3': 'APTO 401 COND. RESID METROPOLI', 'coluna_4': 'Cep', 'coluna_5': '74703-010'}
i = {'Endereço': 'Município', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO', 'coluna_4': '', 'coluna_5': ''}
i = {'Endereço': 'E-mail', 'coluna_1': 'cacaujk322@yahoo.com.br', 'coluna_2': 'Telefone', 'coluna_3': '62992842545', 'coluna_4': 'Tipo Moradia', 'coluna_5': 'Alugada'}
i = {'Endereço': ''}
i = {'Endereço': 'Documento'}
i = {'Endereço': 'Identidade', 'coluna_1': '4293601', 'coluna_2': 'Orgão Expedidor', 'coluna_3': 'Outros Emissores', 'coluna_4': 'Data Expedição', 'coluna_5': '02/12/1998', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'Título', 'coluna_1': '46375431007', 'coluna_2': 'Zona', 'coluna_3': '105', 'coluna_4': 'Seção', 'coluna_5': '0052', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'C.Militar Número', 'coluna_1': '', 'coluna_2': 'C.M. Região', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Endereço': 'NCH Número', 'coluna_1': '', 'coluna_2': 'CNH Validade', 'coluna_3': '', 'coluna_4': 'CNH Dt. Exp', 'coluna_5': '', 'coluna_6': 'CNH Cart.', 'coluna_7': ''}
i = {'Endereço': 'IPASGO', 'coluna_1': '', 'coluna_2': 'PIS/PASEP', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Vínculos': 'Vínculos'}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '', 'coluna_1': '11/12/2007', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'Professor IV', 'coluna_1': '11/12/2007', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': 'PROFESSOR DE 2ª FASE OU ENSINO MÉDIO', 'coluna_1': '01/01/2026', 'coluna_2': '31/12/2026'}
i = {'Dados Pessoais': 'Dados Pessoais'}
i = {'Dados Pessoais': 'CPF', 'coluna_1': '962.313.431-20', 'coluna_2': 'Matrícula Funcional', 'coluna_3': ''}
i = {'Dados Pessoais': 'Nome', 'coluna_1': 'KAREN OLIVEIRA SILVA MATOS', 'coluna_2': 'Data de Nascimento', 'coluna_3': '16/07/1983'}
i = {'Dados Pessoais': 'Naturalidade', 'coluna_1': 'SÃO LUÍS DE MONTES BELOS', 'coluna_2': 'UF', 'coluna_3': 'GO'}
i = {'Dados Pessoais': 'Nacionalidade', 'coluna_1': 'BRASIL', 'coluna_2': 'Sexo', 'coluna_3': 'Feminino'}
i = {'Dados Pessoais': 'Estado Civil', 'coluna_1': 'Casado(a)', 'coluna_2': 'Grau de Instrução', 'coluna_3': 'Educação Superior'}
i = {'Dados Pessoais': 'Pai', 'coluna_1': 'AILTON MIGUEL DA SILVA', 'coluna_2': '', 'coluna_3': ''}
i = {'Dados Pessoais': 'Mãe', 'coluna_1': 'CLEUZA MARCIANO DE OLIVEIRA SILVA', 'coluna_2': '', 'coluna_3': ''}
i = {'Endereço': 'Endereço'}
i = {'Endereço': 'Logradouro', 'coluna_1': 'RUA 13'}
i = {'Endereço': 'Bairro', 'coluna_1': 'CONJUNTO RIVIERA', 'coluna_2': 'Complemento', 'coluna_3': 'QD. 24 LT. 27', 'coluna_4': 'Cep', 'coluna_5': '74730-210'}
i = {'Endereço': 'Município', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO', 'coluna_4': '', 'coluna_5': ''}
i = {'Endereço': 'E-mail', 'coluna_1': 'karenebeto@gmail.com', 'coluna_2': 'Telefone', 'coluna_3': '6238775799', 'coluna_4': 'Tipo Moradia', 'coluna_5': 'Própria'}
i = {'Endereço': ''}
i = {'Endereço': 'Documento'}
i = {'Endereço': 'Identidade', 'coluna_1': '4312304', 'coluna_2': 'Orgão Expedidor', 'coluna_3': 'Outros Emissores', 'coluna_4': 'Data Expedição', 'coluna_5': '25/02/1999', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'Título', 'coluna_1': '44450681007', 'coluna_2': 'Zona', 'coluna_3': '135', 'coluna_4': 'Seção', 'coluna_5': '194', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'C.Militar Número', 'coluna_1': '', 'coluna_2': 'C.M. Região', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Endereço': 'NCH Número', 'coluna_1': '02067020385', 'coluna_2': 'CNH Validade', 'coluna_3': '08/11/2011', 'coluna_4': 'CNH Dt. Exp', 'coluna_5': '09/11/2006', 'coluna_6': 'CNH Cart.', 'coluna_7': 'B'}
i = {'Endereço': 'IPASGO', 'coluna_1': '', 'coluna_2': 'PIS/PASEP', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Vínculos': 'Vínculos'}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '', 'coluna_1': '22/12/2004', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'Professor IV', 'coluna_1': '22/12/2004', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': 'GESTOR ESCOLAR', 'coluna_1': '01/01/2026', 'coluna_2': '31/12/2026'}
i = {'Vínculos': ''}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '70276562', 'coluna_1': '06/01/2005', 'coluna_2': '31/12/2014'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'Professor III', 'coluna_1': '06/01/2005', 'coluna_2': '31/12/2014'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': '-', 'coluna_1': '-', 'coluna_2': '-'}
i = {'Dados Pessoais': 'Dados Pessoais'}
i = {'Dados Pessoais': 'CPF', 'coluna_1': '834.280.381-34', 'coluna_2': 'Matrícula Funcional', 'coluna_3': ''}
i = {'Dados Pessoais': 'Nome', 'coluna_1': 'LIA NUNES FLEURY', 'coluna_2': 'Data de Nascimento', 'coluna_3': '27/08/1979'}
i = {'Dados Pessoais': 'Naturalidade', 'coluna_1': 'CACHOEIRA ALTA', 'coluna_2': 'UF', 'coluna_3': 'GO'}
i = {'Dados Pessoais': 'Nacionalidade', 'coluna_1': 'BRASIL', 'coluna_2': 'Sexo', 'coluna_3': 'Feminino'}
i = {'Dados Pessoais': 'Estado Civil', 'coluna_1': 'Casado(a)', 'coluna_2': 'Grau de Instrução', 'coluna_3': 'Educação Superior'}
i = {'Dados Pessoais': 'Pai', 'coluna_1': 'WILSON GILBERTO DA SILVA FLEURY', 'coluna_2': '', 'coluna_3': ''}
i = {'Dados Pessoais': 'Mãe', 'coluna_1': 'MARIA CONCEICAO NUNES FLEURY', 'coluna_2': '', 'coluna_3': ''}
i = {'Endereço': 'Endereço'}
i = {'Endereço': 'Logradouro', 'coluna_1': 'RUA TURAMACA'}
i = {'Endereço': 'Bairro', 'coluna_1': 'JARDIM CALIFORNIA', 'coluna_2': 'Complemento', 'coluna_3': 'QD.04 LT. 18', 'coluna_4': 'Cep', 'coluna_5': '74730-200'}
i = {'Endereço': 'Município', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO', 'coluna_4': '', 'coluna_5': ''}
i = {'Endereço': 'E-mail', 'coluna_1': 'fleurylia@hotmail.com', 'coluna_2': 'Telefone', 'coluna_3': '6232737015', 'coluna_4': 'Tipo Moradia', 'coluna_5': 'Própria'}
i = {'Endereço': ''}
i = {'Endereço': 'Documento'}
i = {'Endereço': 'Identidade', 'coluna_1': '1068268-6', 'coluna_2': 'Orgão Expedidor', 'coluna_3': 'SSP', 'coluna_4': 'Data Expedição', 'coluna_5': '11/04/1994', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'Título', 'coluna_1': '33944551058', 'coluna_2': 'Zona', 'coluna_3': '096', 'coluna_4': 'Seção', 'coluna_5': '15', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'C.Militar Número', 'coluna_1': '', 'coluna_2': 'C.M. Região', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Endereço': 'NCH Número', 'coluna_1': '', 'coluna_2': 'CNH Validade', 'coluna_3': '', 'coluna_4': 'CNH Dt. Exp', 'coluna_5': '', 'coluna_6': 'CNH Cart.', 'coluna_7': ''}
i = {'Endereço': 'IPASGO', 'coluna_1': '', 'coluna_2': 'PIS/PASEP', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Vínculos': 'Vínculos'}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '', 'coluna_1': '20/02/2004', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'Professor IV', 'coluna_1': '20/02/2004', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': 'PROFESSOR DE 2ª FASE OU ENSINO MÉDIO', 'coluna_1': '01/01/2026', 'coluna_2': '31/12/2026'}
i = {'Vínculos': 'COORDENADOR DE INTEGRAÇÃO CURRICULAR', 'coluna_1': '01/01/2026', 'coluna_2': '31/12/2026'}
i = {'Vínculos': ''}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '59936444', 'coluna_1': '12/03/2004', 'coluna_2': '31/12/2014'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'Professor III', 'coluna_1': '12/03/2004', 'coluna_2': '31/12/2014'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': '-', 'coluna_1': '-', 'coluna_2': '-'}
i = {'Dados Pessoais': 'Dados Pessoais'}
i = {'Dados Pessoais': 'CPF', 'coluna_1': '986.466.801-34', 'coluna_2': 'Matrícula Funcional', 'coluna_3': ''}
i = {'Dados Pessoais': 'Nome', 'coluna_1': 'LILIAN ALVES DE AMORIM SILVA', 'coluna_2': 'Data de Nascimento', 'coluna_3': '16/08/1982'}
i = {'Dados Pessoais': 'Naturalidade', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO'}
i = {'Dados Pessoais': 'Nacionalidade', 'coluna_1': 'BRASIL', 'coluna_2': 'Sexo', 'coluna_3': 'Feminino'}
i = {'Dados Pessoais': 'Estado Civil', 'coluna_1': 'Casado(a)', 'coluna_2': 'Grau de Instrução', 'coluna_3': 'Educação Superior'}
i = {'Dados Pessoais': 'Pai', 'coluna_1': 'José MAuricio de Amorim', 'coluna_2': '', 'coluna_3': ''}
i = {'Dados Pessoais': 'Mãe', 'coluna_1': 'MARIA JOSE ALVES DE AMORIM', 'coluna_2': '', 'coluna_3': ''}
i = {'Endereço': 'Endereço'}
i = {'Endereço': 'Logradouro', 'coluna_1': 'RUA X 4 Qd. X 8 Lt. 274'}
i = {'Endereço': 'Bairro', 'coluna_1': 'Jardim Brasil', 'coluna_2': 'Complemento', 'coluna_3': '', 'coluna_4': 'Cep', 'coluna_5': '74730-360'}
i = {'Endereço': 'Município', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO', 'coluna_4': '', 'coluna_5': ''}
i = {'Endereço': 'E-mail', 'coluna_1': 'lilian_amorim2012@hotmail.com', 'coluna_2': 'Telefone', 'coluna_3': '6281719172', 'coluna_4': 'Tipo Moradia', 'coluna_5': 'Própria'}
i = {'Endereço': ''}
i = {'Endereço': 'Documento'}
i = {'Endereço': 'Identidade', 'coluna_1': '4282738', 'coluna_2': 'Orgão Expedidor', 'coluna_3': 'SSP', 'coluna_4': 'Data Expedição', 'coluna_5': '01/03/2010', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'Título', 'coluna_1': '047608951015', 'coluna_2': 'Zona', 'coluna_3': '135', 'coluna_4': 'Seção', 'coluna_5': '0223', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'C.Militar Número', 'coluna_1': '', 'coluna_2': 'C.M. Região', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Endereço': 'NCH Número', 'coluna_1': '05220924504', 'coluna_2': 'CNH Validade', 'coluna_3': '', 'coluna_4': 'CNH Dt. Exp', 'coluna_5': '', 'coluna_6': 'CNH Cart.', 'coluna_7': ''}
i = {'Endereço': 'IPASGO', 'coluna_1': '404958600', 'coluna_2': 'PIS/PASEP', 'coluna_3': '13011377935', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Vínculos': 'Vínculos'}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '68620552', 'coluna_1': '01/02/2010', 'coluna_2': '31/12/2014'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'Professor III', 'coluna_1': '01/02/2010', 'coluna_2': '23/09/2014'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': '-', 'coluna_1': '-', 'coluna_2': '-'}
i = {'Vínculos': ''}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '', 'coluna_1': '07/10/2010', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'Professor III', 'coluna_1': '07/10/2010', 'coluna_2': '23/09/2014'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': '-', 'coluna_1': '-', 'coluna_2': '-'}
i = {'Vínculos': 'Professor IV', 'coluna_1': '07/10/2010', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': 'PROFESSOR DE 2ª FASE OU ENSINO MÉDIO', 'coluna_1': '01/01/2026', 'coluna_2': '31/12/2026'}
i = {'Vínculos': 'COORDENADOR DE ÁREA - CEPI', 'coluna_1': '01/01/2026', 'coluna_2': '31/12/2026'}
i = {'Dados Pessoais': 'Dados Pessoais'}
i = {'Dados Pessoais': 'CPF', 'coluna_1': '755.247.321-53', 'coluna_2': 'Matrícula Funcional', 'coluna_3': ''}
i = {'Dados Pessoais': 'Nome', 'coluna_1': 'LIVIA PEREIRA NEVES', 'coluna_2': 'Data de Nascimento', 'coluna_3': '10/11/1994'}
i = {'Dados Pessoais': 'Naturalidade', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO'}
i = {'Dados Pessoais': 'Nacionalidade', 'coluna_1': 'BRASIL', 'coluna_2': 'Sexo', 'coluna_3': 'Feminino'}
i = {'Dados Pessoais': 'Estado Civil', 'coluna_1': 'Solteiro(a)', 'coluna_2': 'Grau de Instrução', 'coluna_3': 'Ensino Médio'}
i = {'Dados Pessoais': 'Pai', 'coluna_1': 'WALDEMAR PEREIRA NEVES', 'coluna_2': '', 'coluna_3': ''}
i = {'Dados Pessoais': 'Mãe', 'coluna_1': 'ORLANDA ALVES DE OLIVEIRA NEVES', 'coluna_2': '', 'coluna_3': ''}
i = {'Endereço': 'Endereço'}
i = {'Endereço': 'Logradouro', 'coluna_1': 'Rua JL3'}
i = {'Endereço': 'Bairro', 'coluna_1': 'Jardim Lageado', 'coluna_2': 'Complemento', 'coluna_3': 'QD L-1, LT 24', 'coluna_4': 'Cep', 'coluna_5': '74785-070'}
i = {'Endereço': 'Município', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO', 'coluna_4': '', 'coluna_5': ''}
i = {'Endereço': 'E-mail', 'coluna_1': 'livianevesgeo@gmail.com', 'coluna_2': 'Telefone', 'coluna_3': '62998463692', 'coluna_4': 'Tipo Moradia', 'coluna_5': 'Cedida'}
i = {'Endereço': ''}
i = {'Endereço': 'Documento'}
i = {'Endereço': 'Identidade', 'coluna_1': '5783111', 'coluna_2': 'Orgão Expedidor', 'coluna_3': 'SSP', 'coluna_4': 'Data Expedição', 'coluna_5': '16/10/2015', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'Título', 'coluna_1': '066196951074', 'coluna_2': 'Zona', 'coluna_3': '135', 'coluna_4': 'Seção', 'coluna_5': '0346', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'C.Militar Número', 'coluna_1': '', 'coluna_2': 'C.M. Região', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Endereço': 'NCH Número', 'coluna_1': '06336069100', 'coluna_2': 'CNH Validade', 'coluna_3': '14/01/2025', 'coluna_4': 'CNH Dt. Exp', 'coluna_5': '15/01/2020', 'coluna_6': 'CNH Cart.', 'coluna_7': 'AB'}
i = {'Endereço': 'IPASGO', 'coluna_1': '', 'coluna_2': 'PIS/PASEP', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Vínculos': 'Vínculos'}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '', 'coluna_1': '02/03/2022', 'coluna_2': '08/04/2024'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'C.Temporário - Apoio Administrativo - Nível Médio - SEDUCE', 'coluna_1': '02/03/2022', 'coluna_2': '08/04/2024'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': '-', 'coluna_1': '-', 'coluna_2': '-'}
i = {'Vínculos': ''}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '', 'coluna_1': '08/04/2024', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'C.Temporário - Apoio Administrativo - Nível Fundamental - SEDUC', 'coluna_1': '08/04/2024', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': 'LABORATORISTA', 'coluna_1': '01/01/2026', 'coluna_2': '31/12/2026'}
i = {'Dados Pessoais': 'Dados Pessoais'}
i = {'Dados Pessoais': 'CPF', 'coluna_1': '771.762.001-49', 'coluna_2': 'Matrícula Funcional', 'coluna_3': '55218401'}
i = {'Dados Pessoais': 'Nome', 'coluna_1': 'LUZIA VIEIRA DA SILVA', 'coluna_2': 'Data de Nascimento', 'coluna_3': '06/12/1963'}
i = {'Dados Pessoais': 'Naturalidade', 'coluna_1': 'BELA VISTA DE GOIÁS', 'coluna_2': 'UF', 'coluna_3': 'GO'}
i = {'Dados Pessoais': 'Nacionalidade', 'coluna_1': 'BRASIL', 'coluna_2': 'Sexo', 'coluna_3': 'Feminino'}
i = {'Dados Pessoais': 'Estado Civil', 'coluna_1': 'Solteiro(a)', 'coluna_2': 'Grau de Instrução', 'coluna_3': 'Fundamental'}
i = {'Dados Pessoais': 'Pai', 'coluna_1': 'ISRAEL VIEIRA DA SILVA', 'coluna_2': '', 'coluna_3': ''}
i = {'Dados Pessoais': 'Mãe', 'coluna_1': 'SANTA CLEMENTINA DA SILVA', 'coluna_2': '', 'coluna_3': ''}
i = {'Endereço': 'Endereço'}
i = {'Endereço': 'Logradouro', 'coluna_1': 'RUA BLUMENAL'}
i = {'Endereço': 'Bairro', 'coluna_1': 'JARDIM NOVO MUNDO', 'coluna_2': 'Complemento', 'coluna_3': 'QD.46 LT.07', 'coluna_4': 'Cep', 'coluna_5': '74715-080'}
i = {'Endereço': 'Município', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO', 'coluna_4': '', 'coluna_5': ''}
i = {'Endereço': 'E-mail', 'coluna_1': '', 'coluna_2': 'Telefone', 'coluna_3': '62995611631', 'coluna_4': 'Tipo Moradia', 'coluna_5': 'Própria'}
i = {'Endereço': ''}
i = {'Endereço': 'Documento'}
i = {'Endereço': 'Identidade', 'coluna_1': '1472798', 'coluna_2': 'Orgão Expedidor', 'coluna_3': 'Outros Emissores', 'coluna_4': 'Data Expedição', 'coluna_5': '20/03/1982', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'Título', 'coluna_1': '19778791015', 'coluna_2': 'Zona', 'coluna_3': '135', 'coluna_4': 'Seção', 'coluna_5': '48', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'C.Militar Número', 'coluna_1': '', 'coluna_2': 'C.M. Região', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Endereço': 'NCH Número', 'coluna_1': '', 'coluna_2': 'CNH Validade', 'coluna_3': '', 'coluna_4': 'CNH Dt. Exp', 'coluna_5': '', 'coluna_6': 'CNH Cart.', 'coluna_7': ''}
i = {'Endereço': 'IPASGO', 'coluna_1': '2227231', 'coluna_2': 'PIS/PASEP', 'coluna_3': '17054880070', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Vínculos': 'Vínculos'}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '', 'coluna_1': '03/11/1993', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'Agente Administrativo Educacional Apoio (A)', 'coluna_1': '03/11/1993', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': 'EXECUTOR DE SERVIÇOS AUXILIARES', 'coluna_1': '01/01/2026', 'coluna_2': '31/12/2026'}
i = {'Dados Pessoais': 'Dados Pessoais'}
i = {'Dados Pessoais': 'CPF', 'coluna_1': '380.653.471-34', 'coluna_2': 'Matrícula Funcional', 'coluna_3': ''}
i = {'Dados Pessoais': 'Nome', 'coluna_1': 'LUZIMEIRE DIVINA PEREIRA VELOSO', 'coluna_2': 'Data de Nascimento', 'coluna_3': '20/07/1968'}
i = {'Dados Pessoais': 'Naturalidade', 'coluna_1': '', 'coluna_2': 'UF', 'coluna_3': ''}
i = {'Dados Pessoais': 'Nacionalidade', 'coluna_1': '', 'coluna_2': 'Sexo', 'coluna_3': 'Feminino'}
i = {'Dados Pessoais': 'Estado Civil', 'coluna_1': 'Não informado', 'coluna_2': 'Grau de Instrução', 'coluna_3': ''}
i = {'Dados Pessoais': 'Pai', 'coluna_1': '', 'coluna_2': '', 'coluna_3': ''}
i = {'Dados Pessoais': 'Mãe', 'coluna_1': 'CIRA LEITE PEREIRA', 'coluna_2': '', 'coluna_3': ''}
i = {'Endereço': 'Endereço'}
i = {'Endereço': 'Logradouro', 'coluna_1': ''}
i = {'Endereço': 'Bairro', 'coluna_1': '', 'coluna_2': 'Complemento', 'coluna_3': '', 'coluna_4': 'Cep', 'coluna_5': ''}
i = {'Endereço': 'Município', 'coluna_1': '', 'coluna_2': 'UF', 'coluna_3': '', 'coluna_4': '', 'coluna_5': ''}
i = {'Endereço': 'E-mail', 'coluna_1': '', 'coluna_2': 'Telefone', 'coluna_3': '', 'coluna_4': 'Tipo Moradia', 'coluna_5': ''}
i = {'Endereço': ''}
i = {'Endereço': 'Documento'}
i = {'Endereço': 'Identidade', 'coluna_1': '', 'coluna_2': 'Orgão Expedidor', 'coluna_3': '', 'coluna_4': 'Data Expedição', 'coluna_5': '', 'coluna_6': 'UF', 'coluna_7': ''}
i = {'Endereço': 'Título', 'coluna_1': '', 'coluna_2': 'Zona', 'coluna_3': '', 'coluna_4': 'Seção', 'coluna_5': '', 'coluna_6': 'UF', 'coluna_7': ''}
i = {'Endereço': 'C.Militar Número', 'coluna_1': '', 'coluna_2': 'C.M. Região', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Endereço': 'NCH Número', 'coluna_1': '', 'coluna_2': 'CNH Validade', 'coluna_3': '', 'coluna_4': 'CNH Dt. Exp', 'coluna_5': '', 'coluna_6': 'CNH Cart.', 'coluna_7': ''}
i = {'Endereço': 'IPASGO', 'coluna_1': '', 'coluna_2': 'PIS/PASEP', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Vínculos': 'Vínculos'}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '', 'coluna_1': '01/07/2022', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'C.Temporário - Apoio Administrativo - Nível Fundamental - SEDUC', 'coluna_1': '01/07/2022', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': 'EXECUTOR DE SERVIÇOS AUXILIARES', 'coluna_1': '01/01/2026', 'coluna_2': '31/12/2026'}
i = {'Dados Pessoais': 'Dados Pessoais'}
i = {'Dados Pessoais': 'CPF', 'coluna_1': '243.522.681-00', 'coluna_2': 'Matrícula Funcional', 'coluna_3': ''}
i = {'Dados Pessoais': 'Nome', 'coluna_1': 'MARIA APARECIDA PEREIRA DO NASCIMENTO', 'coluna_2': 'Data de Nascimento', 'coluna_3': '12/01/1959'}
i = {'Dados Pessoais': 'Naturalidade', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO'}
i = {'Dados Pessoais': 'Nacionalidade', 'coluna_1': 'BRASIL', 'coluna_2': 'Sexo', 'coluna_3': 'Feminino'}
i = {'Dados Pessoais': 'Estado Civil', 'coluna_1': 'Solteiro(a)', 'coluna_2': 'Grau de Instrução', 'coluna_3': 'Educação Superior'}
i = {'Dados Pessoais': 'Pai', 'coluna_1': 'JOÃO PEREIRA DO NASCIMENTO', 'coluna_2': '', 'coluna_3': ''}
i = {'Dados Pessoais': 'Mãe', 'coluna_1': 'MARIA FERREIRA DO NASCIMENTO', 'coluna_2': '', 'coluna_3': ''}
i = {'Endereço': 'Endereço'}
i = {'Endereço': 'Logradouro', 'coluna_1': 'RUA D QUADRA E'}
i = {'Endereço': 'Bairro', 'coluna_1': 'VILA AL COSME', 'coluna_2': 'Complemento', 'coluna_3': 'RESIDENCIAL DOURADO BLC.14 APT', 'coluna_4': 'Cep', 'coluna_5': '74635-075'}
i = {'Endereço': 'Município', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO', 'coluna_4': '', 'coluna_5': ''}
i = {'Endereço': 'E-mail', 'coluna_1': '', 'coluna_2': 'Telefone', 'coluna_3': '62981520471', 'coluna_4': 'Tipo Moradia', 'coluna_5': 'Própria'}
i = {'Endereço': ''}
i = {'Endereço': 'Documento'}
i = {'Endereço': 'Identidade', 'coluna_1': '1067724', 'coluna_2': 'Orgão Expedidor', 'coluna_3': 'SSP', 'coluna_4': 'Data Expedição', 'coluna_5': '07/07/2003', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'Título', 'coluna_1': '20492791007', 'coluna_2': 'Zona', 'coluna_3': '135', 'coluna_4': 'Seção', 'coluna_5': '67', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'C.Militar Número', 'coluna_1': '', 'coluna_2': 'C.M. Região', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Endereço': 'NCH Número', 'coluna_1': '', 'coluna_2': 'CNH Validade', 'coluna_3': '', 'coluna_4': 'CNH Dt. Exp', 'coluna_5': '', 'coluna_6': 'CNH Cart.', 'coluna_7': ''}
i = {'Endereço': 'IPASGO', 'coluna_1': '002843960', 'coluna_2': 'PIS/PASEP', 'coluna_3': '10791482372', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Vínculos': 'Vínculos'}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '', 'coluna_1': '22/12/2004', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'Professor IV', 'coluna_1': '22/12/2004', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': 'PROFESSOR DE 2ª FASE OU ENSINO MÉDIO', 'coluna_1': '01/01/2026', 'coluna_2': '31/12/2026'}
i = {'Dados Pessoais': 'Dados Pessoais'}
i = {'Dados Pessoais': 'CPF', 'coluna_1': '875.336.691-34', 'coluna_2': 'Matrícula Funcional', 'coluna_3': ''}
i = {'Dados Pessoais': 'Nome', 'coluna_1': 'MARIA DE FATIMA FLOR DE OLIVEIRA', 'coluna_2': 'Data de Nascimento', 'coluna_3': '23/04/1963'}
i = {'Dados Pessoais': 'Naturalidade', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO'}
i = {'Dados Pessoais': 'Nacionalidade', 'coluna_1': 'BRASIL', 'coluna_2': 'Sexo', 'coluna_3': 'Feminino'}
i = {'Dados Pessoais': 'Estado Civil', 'coluna_1': 'Casado(a)', 'coluna_2': 'Grau de Instrução', 'coluna_3': 'Educação Superior'}
i = {'Dados Pessoais': 'Pai', 'coluna_1': 'CICERO FLOR DE MEDEIROS', 'coluna_2': '', 'coluna_3': ''}
i = {'Dados Pessoais': 'Mãe', 'coluna_1': 'MARIA SALETE FLOR', 'coluna_2': '', 'coluna_3': ''}
i = {'Endereço': 'Endereço'}
i = {'Endereço': 'Logradouro', 'coluna_1': 'AV. SAN MARTINS'}
i = {'Endereço': 'Bairro', 'coluna_1': 'JARDIM NOVO MUNDO', 'coluna_2': 'Complemento', 'coluna_3': 'QD 170 LT 02', 'coluna_4': 'Cep', 'coluna_5': '74710-040'}
i = {'Endereço': 'Município', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO', 'coluna_4': '', 'coluna_5': ''}
i = {'Endereço': 'E-mail', 'coluna_1': 'fortimafloroliveira@hotmail.com.br', 'coluna_2': 'Telefone', 'coluna_3': '6232061718', 'coluna_4': 'Tipo Moradia', 'coluna_5': 'Própria'}
i = {'Endereço': ''}
i = {'Endereço': 'Documento'}
i = {'Endereço': 'Identidade', 'coluna_1': '1425452', 'coluna_2': 'Orgão Expedidor', 'coluna_3': 'SSP', 'coluna_4': 'Data Expedição', 'coluna_5': '30/11/1990', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'Título', 'coluna_1': '019205051082', 'coluna_2': 'Zona', 'coluna_3': '135', 'coluna_4': 'Seção', 'coluna_5': '59', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'C.Militar Número', 'coluna_1': '', 'coluna_2': 'C.M. Região', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Endereço': 'NCH Número', 'coluna_1': '', 'coluna_2': 'CNH Validade', 'coluna_3': '', 'coluna_4': 'CNH Dt. Exp', 'coluna_5': '', 'coluna_6': 'CNH Cart.', 'coluna_7': ''}
i = {'Endereço': 'IPASGO', 'coluna_1': '', 'coluna_2': 'PIS/PASEP', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Vínculos': 'Vínculos'}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '', 'coluna_1': '01/11/2006', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'Professor IV', 'coluna_1': '01/11/2006', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': 'PROFISSIONAL DE APOIO ESCOLAR', 'coluna_1': '20/02/2026', 'coluna_2': '31/12/2026'}
i = {'Dados Pessoais': 'Dados Pessoais'}
i = {'Dados Pessoais': 'CPF', 'coluna_1': '471.156.101-34', 'coluna_2': 'Matrícula Funcional', 'coluna_3': '8.289'}
i = {'Dados Pessoais': 'Nome', 'coluna_1': 'MARIA ELMA CARDOSO DOS SANTOS', 'coluna_2': 'Data de Nascimento', 'coluna_3': '16/06/1970'}
i = {'Dados Pessoais': 'Naturalidade', 'coluna_1': 'JANUÁRIA', 'coluna_2': 'UF', 'coluna_3': 'MG'}
i = {'Dados Pessoais': 'Nacionalidade', 'coluna_1': 'BRASIL', 'coluna_2': 'Sexo', 'coluna_3': 'Feminino'}
i = {'Dados Pessoais': 'Estado Civil', 'coluna_1': 'Casado(a)', 'coluna_2': 'Grau de Instrução', 'coluna_3': 'Ensino Médio'}
i = {'Dados Pessoais': 'Pai', 'coluna_1': 'MARTINHO CARDOSO DOS SANTOS', 'coluna_2': '', 'coluna_3': ''}
i = {'Dados Pessoais': 'Mãe', 'coluna_1': 'SENHORINHA CORREA MENEZES', 'coluna_2': '', 'coluna_3': ''}
i = {'Endereço': 'Endereço'}
i = {'Endereço': 'Logradouro', 'coluna_1': 'AVENIDA TOPÁZIO'}
i = {'Endereço': 'Bairro', 'coluna_1': 'JARDIM CALIFORNIA', 'coluna_2': 'Complemento', 'coluna_3': 'QUADRA 22LOTE 29', 'coluna_4': 'Cep', 'coluna_5': '74735-170'}
i = {'Endereço': 'Município', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO', 'coluna_4': '', 'coluna_5': ''}
i = {'Endereço': 'E-mail', 'coluna_1': 'mariacardoso1971@gmail.com', 'coluna_2': 'Telefone', 'coluna_3': '6292436755', 'coluna_4': 'Tipo Moradia', 'coluna_5': 'Própria'}
i = {'Endereço': ''}
i = {'Endereço': 'Documento'}
i = {'Endereço': 'Identidade', 'coluna_1': '1958856 2ª via', 'coluna_2': 'Orgão Expedidor', 'coluna_3': 'SSP', 'coluna_4': 'Data Expedição', 'coluna_5': '11/08/2010', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'Título', 'coluna_1': '26229491082', 'coluna_2': 'Zona', 'coluna_3': '135', 'coluna_4': 'Seção', 'coluna_5': '20', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'C.Militar Número', 'coluna_1': '', 'coluna_2': 'C.M. Região', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Endereço': 'NCH Número', 'coluna_1': '', 'coluna_2': 'CNH Validade', 'coluna_3': '', 'coluna_4': 'CNH Dt. Exp', 'coluna_5': '', 'coluna_6': 'CNH Cart.', 'coluna_7': ''}
i = {'Endereço': 'IPASGO', 'coluna_1': '2379147-00', 'coluna_2': 'PIS/PASEP', 'coluna_3': '12316594524', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Vínculos': 'Vínculos'}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '', 'coluna_1': '04/10/1994', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'Agente Administrativo Educacional Apoio (A)', 'coluna_1': '04/10/1994', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': 'EXECUTOR DE SERVIÇOS ADMINISTRATIVOS', 'coluna_1': '01/01/2026', 'coluna_2': '31/12/2026'}
i = {'Dados Pessoais': 'Dados Pessoais'}
i = {'Dados Pessoais': 'CPF', 'coluna_1': '491.723.791-20', 'coluna_2': 'Matrícula Funcional', 'coluna_3': '30494'}
i = {'Dados Pessoais': 'Nome', 'coluna_1': 'MARLI VITALINO DA SILVA', 'coluna_2': 'Data de Nascimento', 'coluna_3': '04/01/1965'}
i = {'Dados Pessoais': 'Naturalidade', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO'}
i = {'Dados Pessoais': 'Nacionalidade', 'coluna_1': 'BRASIL', 'coluna_2': 'Sexo', 'coluna_3': 'Feminino'}
i = {'Dados Pessoais': 'Estado Civil', 'coluna_1': 'Não informado', 'coluna_2': 'Grau de Instrução', 'coluna_3': 'Fundamental'}
i = {'Dados Pessoais': 'Pai', 'coluna_1': 'GILBERTO VITALINO DA SOLVA', 'coluna_2': '', 'coluna_3': ''}
i = {'Dados Pessoais': 'Mãe', 'coluna_1': 'RITA MARIA DA CONCEICAO', 'coluna_2': '', 'coluna_3': ''}
i = {'Endereço': 'Endereço'}
i = {'Endereço': 'Logradouro', 'coluna_1': 'R ARAGUAIANA'}
i = {'Endereço': 'Bairro', 'coluna_1': 'JD CALIFÓRNIA', 'coluna_2': 'Complemento', 'coluna_3': 'Q 17 L 9', 'coluna_4': 'Cep', 'coluna_5': '74730-130'}
i = {'Endereço': 'Município', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO', 'coluna_4': '', 'coluna_5': ''}
i = {'Endereço': 'E-mail', 'coluna_1': '', 'coluna_2': 'Telefone', 'coluna_3': '62992967380', 'coluna_4': 'Tipo Moradia', 'coluna_5': 'Própria'}
i = {'Endereço': ''}
i = {'Endereço': 'Documento'}
i = {'Endereço': 'Identidade', 'coluna_1': '1890344', 'coluna_2': 'Orgão Expedidor', 'coluna_3': 'SSP', 'coluna_4': 'Data Expedição', 'coluna_5': '21/10/1986', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'Título', 'coluna_1': '032009281031', 'coluna_2': 'Zona', 'coluna_3': '135', 'coluna_4': 'Seção', 'coluna_5': '26', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'C.Militar Número', 'coluna_1': '', 'coluna_2': 'C.M. Região', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Endereço': 'NCH Número', 'coluna_1': '', 'coluna_2': 'CNH Validade', 'coluna_3': '', 'coluna_4': 'CNH Dt. Exp', 'coluna_5': '', 'coluna_6': 'CNH Cart.', 'coluna_7': ''}
i = {'Endereço': 'IPASGO', 'coluna_1': '2474026', 'coluna_2': 'PIS/PASEP', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Vínculos': 'Vínculos'}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '56374901', 'coluna_1': '27/07/1994', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'Agente Administrativo Educacional Apoio (A)', 'coluna_1': '27/07/1994', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': 'MERENDEIRA', 'coluna_1': '01/01/2026', 'coluna_2': '31/12/2026'}
i = {'Dados Pessoais': 'Dados Pessoais'}
i = {'Dados Pessoais': 'CPF', 'coluna_1': '517.767.401-06', 'coluna_2': 'Matrícula Funcional', 'coluna_3': '34825'}
i = {'Dados Pessoais': 'Nome', 'coluna_1': 'NARA GONZAGA DA SILVA', 'coluna_2': 'Data de Nascimento', 'coluna_3': '30/10/1970'}
i = {'Dados Pessoais': 'Naturalidade', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO'}
i = {'Dados Pessoais': 'Nacionalidade', 'coluna_1': 'BRASIL', 'coluna_2': 'Sexo', 'coluna_3': 'Feminino'}
i = {'Dados Pessoais': 'Estado Civil', 'coluna_1': 'Divorciado(a)', 'coluna_2': 'Grau de Instrução', 'coluna_3': 'Educação Superior'}
i = {'Dados Pessoais': 'Pai', 'coluna_1': 'LUIZ GONZAGA DA SILVA', 'coluna_2': '', 'coluna_3': ''}
i = {'Dados Pessoais': 'Mãe', 'coluna_1': 'ROMILDA CARRIJO DA SILVA', 'coluna_2': '', 'coluna_3': ''}
i = {'Endereço': 'Endereço'}
i = {'Endereço': 'Logradouro', 'coluna_1': 'fazenda val das pombas'}
i = {'Endereço': 'Bairro', 'coluna_1': 'vau das pombas', 'coluna_2': 'Complemento', 'coluna_3': 'estrada velha bela vista', 'coluna_4': 'Cep', 'coluna_5': '74891-130'}
i = {'Endereço': 'Município', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO', 'coluna_4': '', 'coluna_5': ''}
i = {'Endereço': 'E-mail', 'coluna_1': 'nara.aguiar@seduc.go.gov.br', 'coluna_2': 'Telefone', 'coluna_3': '62968490404', 'coluna_4': 'Tipo Moradia', 'coluna_5': 'Alugada'}
i = {'Endereço': ''}
i = {'Endereço': 'Documento'}
i = {'Endereço': 'Identidade', 'coluna_1': '2104466', 'coluna_2': 'Orgão Expedidor', 'coluna_3': 'SSP', 'coluna_4': 'Data Expedição', 'coluna_5': '12/09/2008', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'Título', 'coluna_1': '027589791007', 'coluna_2': 'Zona', 'coluna_3': '040', 'coluna_4': 'Seção', 'coluna_5': '22', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'C.Militar Número', 'coluna_1': '', 'coluna_2': 'C.M. Região', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Endereço': 'NCH Número', 'coluna_1': '', 'coluna_2': 'CNH Validade', 'coluna_3': '', 'coluna_4': 'CNH Dt. Exp', 'coluna_5': '', 'coluna_6': 'CNH Cart.', 'coluna_7': ''}
i = {'Endereço': 'IPASGO', 'coluna_1': '2503905', 'coluna_2': 'PIS/PASEP', 'coluna_3': '26919370387', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Vínculos': 'Vínculos'}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '', 'coluna_1': '03/08/1999', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'Professor IV', 'coluna_1': '03/08/1999', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': 'PROFESSOR DE 2ª FASE OU ENSINO MÉDIO', 'coluna_1': '01/01/2026', 'coluna_2': '31/12/2026'}
i = {'Dados Pessoais': 'Dados Pessoais'}
i = {'Dados Pessoais': 'CPF', 'coluna_1': '802.930.181-20', 'coluna_2': 'Matrícula Funcional', 'coluna_3': ''}
i = {'Dados Pessoais': 'Nome', 'coluna_1': 'NUBIA ARIANE FEITOSA MELO', 'coluna_2': 'Data de Nascimento', 'coluna_3': '26/08/1975'}
i = {'Dados Pessoais': 'Naturalidade', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO'}
i = {'Dados Pessoais': 'Nacionalidade', 'coluna_1': 'BRASIL', 'coluna_2': 'Sexo', 'coluna_3': 'Feminino'}
i = {'Dados Pessoais': 'Estado Civil', 'coluna_1': 'Casado(a)', 'coluna_2': 'Grau de Instrução', 'coluna_3': 'Educação Superior'}
i = {'Dados Pessoais': 'Pai', 'coluna_1': 'MANOEL MARIANO FEITOSA', 'coluna_2': '', 'coluna_3': ''}
i = {'Dados Pessoais': 'Mãe', 'coluna_1': 'MARIA ALVES FEITOSA', 'coluna_2': '', 'coluna_3': ''}
i = {'Endereço': 'Endereço'}
i = {'Endereço': 'Logradouro', 'coluna_1': 'RUA LIBERDADE'}
i = {'Endereço': 'Bairro', 'coluna_1': 'VILA MARTINS', 'coluna_2': 'Complemento', 'coluna_3': 'BL C APART 301', 'coluna_4': 'Cep', 'coluna_5': '74703-210'}
i = {'Endereço': 'Município', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO', 'coluna_4': '', 'coluna_5': ''}
i = {'Endereço': 'E-mail', 'coluna_1': 'secretarianubiamelo@gmail.com', 'coluna_2': 'Telefone', 'coluna_3': '6284579864', 'coluna_4': 'Tipo Moradia', 'coluna_5': 'Alugada'}
i = {'Endereço': ''}
i = {'Endereço': 'Documento'}
i = {'Endereço': 'Identidade', 'coluna_1': '3393739', 'coluna_2': 'Orgão Expedidor', 'coluna_3': 'SSP', 'coluna_4': 'Data Expedição', 'coluna_5': '10/07/1997', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'Título', 'coluna_1': '33483971031', 'coluna_2': 'Zona', 'coluna_3': '135', 'coluna_4': 'Seção', 'coluna_5': '26', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'C.Militar Número', 'coluna_1': '', 'coluna_2': 'C.M. Região', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Endereço': 'NCH Número', 'coluna_1': '', 'coluna_2': 'CNH Validade', 'coluna_3': '', 'coluna_4': 'CNH Dt. Exp', 'coluna_5': '', 'coluna_6': 'CNH Cart.', 'coluna_7': ''}
i = {'Endereço': 'IPASGO', 'coluna_1': '', 'coluna_2': 'PIS/PASEP', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Vínculos': 'Vínculos'}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '59075191', 'coluna_1': '02/08/1999', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'Professor III', 'coluna_1': '02/08/1999', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': 'SECRETÁRIO ESCOLAR', 'coluna_1': '01/01/2026', 'coluna_2': '31/12/2026'}
i = {'Dados Pessoais': 'Dados Pessoais'}
i = {'Dados Pessoais': 'CPF', 'coluna_1': '010.870.001-14', 'coluna_2': 'Matrícula Funcional', 'coluna_3': ''}
i = {'Dados Pessoais': 'Nome', 'coluna_1': 'POLIANA ANGELICA DE JESUS', 'coluna_2': 'Data de Nascimento', 'coluna_3': '20/12/1984'}
i = {'Dados Pessoais': 'Naturalidade', 'coluna_1': '', 'coluna_2': 'UF', 'coluna_3': ''}
i = {'Dados Pessoais': 'Nacionalidade', 'coluna_1': '', 'coluna_2': 'Sexo', 'coluna_3': 'Feminino'}
i = {'Dados Pessoais': 'Estado Civil', 'coluna_1': 'Não informado', 'coluna_2': 'Grau de Instrução', 'coluna_3': ''}
i = {'Dados Pessoais': 'Pai', 'coluna_1': '', 'coluna_2': '', 'coluna_3': ''}
i = {'Dados Pessoais': 'Mãe', 'coluna_1': 'ESTER ANGELICA DE JESUS', 'coluna_2': '', 'coluna_3': ''}
i = {'Endereço': 'Endereço'}
i = {'Endereço': 'Logradouro', 'coluna_1': ''}
i = {'Endereço': 'Bairro', 'coluna_1': '', 'coluna_2': 'Complemento', 'coluna_3': '', 'coluna_4': 'Cep', 'coluna_5': ''}
i = {'Endereço': 'Município', 'coluna_1': '', 'coluna_2': 'UF', 'coluna_3': '', 'coluna_4': '', 'coluna_5': ''}
i = {'Endereço': 'E-mail', 'coluna_1': '', 'coluna_2': 'Telefone', 'coluna_3': '', 'coluna_4': 'Tipo Moradia', 'coluna_5': ''}
i = {'Endereço': ''}
i = {'Endereço': 'Documento'}
i = {'Endereço': 'Identidade', 'coluna_1': '', 'coluna_2': 'Orgão Expedidor', 'coluna_3': '', 'coluna_4': 'Data Expedição', 'coluna_5': '', 'coluna_6': 'UF', 'coluna_7': ''}
i = {'Endereço': 'Título', 'coluna_1': '', 'coluna_2': 'Zona', 'coluna_3': '', 'coluna_4': 'Seção', 'coluna_5': '', 'coluna_6': 'UF', 'coluna_7': ''}
i = {'Endereço': 'C.Militar Número', 'coluna_1': '', 'coluna_2': 'C.M. Região', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Endereço': 'NCH Número', 'coluna_1': '', 'coluna_2': 'CNH Validade', 'coluna_3': '', 'coluna_4': 'CNH Dt. Exp', 'coluna_5': '', 'coluna_6': 'CNH Cart.', 'coluna_7': ''}
i = {'Endereço': 'IPASGO', 'coluna_1': '', 'coluna_2': 'PIS/PASEP', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Vínculos': 'Vínculos'}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '', 'coluna_1': '01/09/2025', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'C.Temporário - Apoio Administrativo - Nível Fundamental - SEDUC', 'coluna_1': '01/09/2025', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': 'MERENDEIRA', 'coluna_1': '01/01/2026', 'coluna_2': '31/12/2026'}
i = {'Dados Pessoais': 'Dados Pessoais'}
i = {'Dados Pessoais': 'CPF', 'coluna_1': '520.010.831-49', 'coluna_2': 'Matrícula Funcional', 'coluna_3': ''}
i = {'Dados Pessoais': 'Nome', 'coluna_1': 'REINALDO NOGUEIRA DOS SANTOS', 'coluna_2': 'Data de Nascimento', 'coluna_3': '06/01/1967'}
i = {'Dados Pessoais': 'Naturalidade', 'coluna_1': 'SANTA MARIA DA VITÓRIA', 'coluna_2': 'UF', 'coluna_3': 'BA'}
i = {'Dados Pessoais': 'Nacionalidade', 'coluna_1': 'BRASIL', 'coluna_2': 'Sexo', 'coluna_3': 'Masculino'}
i = {'Dados Pessoais': 'Estado Civil', 'coluna_1': 'Solteiro(a)', 'coluna_2': 'Grau de Instrução', 'coluna_3': 'Ensino Médio'}
i = {'Dados Pessoais': 'Pai', 'coluna_1': '', 'coluna_2': '', 'coluna_3': ''}
i = {'Dados Pessoais': 'Mãe', 'coluna_1': 'ALZIRA MARIA DOS SANTOS', 'coluna_2': '', 'coluna_3': ''}
i = {'Endereço': 'Endereço'}
i = {'Endereço': 'Logradouro', 'coluna_1': 'rua 11 qe 2 l10'}
i = {'Endereço': 'Bairro', 'coluna_1': 'vila pedroso', 'coluna_2': 'Complemento', 'coluna_3': '00', 'coluna_4': 'Cep', 'coluna_5': '74770-250'}
i = {'Endereço': 'Município', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO', 'coluna_4': '', 'coluna_5': ''}
i = {'Endereço': 'E-mail', 'coluna_1': '', 'coluna_2': 'Telefone', 'coluna_3': '6299085316', 'coluna_4': 'Tipo Moradia', 'coluna_5': 'Própria'}
i = {'Endereço': ''}
i = {'Endereço': 'Documento'}
i = {'Endereço': 'Identidade', 'coluna_1': '1561976', 'coluna_2': 'Orgão Expedidor', 'coluna_3': 'SSP', 'coluna_4': 'Data Expedição', 'coluna_5': '20/02/2011', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'Título', 'coluna_1': '020328981023', 'coluna_2': 'Zona', 'coluna_3': '135', 'coluna_4': 'Seção', 'coluna_5': '0251', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'C.Militar Número', 'coluna_1': '', 'coluna_2': 'C.M. Região', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Endereço': 'NCH Número', 'coluna_1': '', 'coluna_2': 'CNH Validade', 'coluna_3': '', 'coluna_4': 'CNH Dt. Exp', 'coluna_5': '', 'coluna_6': 'CNH Cart.', 'coluna_7': ''}
i = {'Endereço': 'IPASGO', 'coluna_1': '', 'coluna_2': 'PIS/PASEP', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Vínculos': 'Vínculos'}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '', 'coluna_1': '01/03/2021', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'C.Temporário - Apoio Administrativo - Nível Fundamental - SEDUC', 'coluna_1': '01/03/2021', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': 'VIGIA', 'coluna_1': '01/01/2026', 'coluna_2': '31/12/2026'}
i = {'Dados Pessoais': 'Dados Pessoais'}
i = {'Dados Pessoais': 'CPF', 'coluna_1': '862.849.831-15', 'coluna_2': 'Matrícula Funcional', 'coluna_3': ''}
i = {'Dados Pessoais': 'Nome', 'coluna_1': 'ROBERTA PEREIRA VILELA', 'coluna_2': 'Data de Nascimento', 'coluna_3': '27/07/1978'}
i = {'Dados Pessoais': 'Naturalidade', 'coluna_1': 'PALMEIRAS DE GOIÁS', 'coluna_2': 'UF', 'coluna_3': 'GO'}
i = {'Dados Pessoais': 'Nacionalidade', 'coluna_1': 'BRASIL', 'coluna_2': 'Sexo', 'coluna_3': 'Feminino'}
i = {'Dados Pessoais': 'Estado Civil', 'coluna_1': 'Solteiro(a)', 'coluna_2': 'Grau de Instrução', 'coluna_3': 'Educação Superior'}
i = {'Dados Pessoais': 'Pai', 'coluna_1': 'DIVINO ALVES VILELA', 'coluna_2': '', 'coluna_3': ''}
i = {'Dados Pessoais': 'Mãe', 'coluna_1': 'CRISTINA PEREIRA VILELA', 'coluna_2': '', 'coluna_3': ''}
i = {'Endereço': 'Endereço'}
i = {'Endereço': 'Logradouro', 'coluna_1': 'RUA 3 LT 23 UNIDADE 207'}
i = {'Endereço': 'Bairro', 'coluna_1': 'PARQUE ATENEU', 'coluna_2': 'Complemento', 'coluna_3': '', 'coluna_4': 'Cep', 'coluna_5': '74893-160'}
i = {'Endereço': 'Município', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO', 'coluna_4': '', 'coluna_5': ''}
i = {'Endereço': 'E-mail', 'coluna_1': 'robertavile@hotmail.com', 'coluna_2': 'Telefone', 'coluna_3': '6284347882', 'coluna_4': 'Tipo Moradia', 'coluna_5': 'Própria'}
i = {'Endereço': ''}
i = {'Endereço': 'Documento'}
i = {'Endereço': 'Identidade', 'coluna_1': '3404559', 'coluna_2': 'Orgão Expedidor', 'coluna_3': 'SSP', 'coluna_4': 'Data Expedição', 'coluna_5': '06/10/1992', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'Título', 'coluna_1': '039358971066', 'coluna_2': 'Zona', 'coluna_3': '127', 'coluna_4': 'Seção', 'coluna_5': '63', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'C.Militar Número', 'coluna_1': '', 'coluna_2': 'C.M. Região', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Endereço': 'NCH Número', 'coluna_1': '', 'coluna_2': 'CNH Validade', 'coluna_3': '', 'coluna_4': 'CNH Dt. Exp', 'coluna_5': '', 'coluna_6': 'CNH Cart.', 'coluna_7': ''}
i = {'Endereço': 'IPASGO', 'coluna_1': '', 'coluna_2': 'PIS/PASEP', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Vínculos': 'Vínculos'}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '', 'coluna_1': '22/12/2004', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'Professor III', 'coluna_1': '22/12/2004', 'coluna_2': '21/06/2022'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': '-', 'coluna_1': '-', 'coluna_2': '-'}
i = {'Vínculos': 'Professor IV', 'coluna_1': '22/12/2004', 'coluna_2': '21/06/2022'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': '-', 'coluna_1': '-', 'coluna_2': '-'}
i = {'Vínculos': ''}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '', 'coluna_1': '23/12/2004', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'Professor IV', 'coluna_1': '23/12/2004', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': 'DINAMIZADOR DE BIBLIOTECA', 'coluna_1': '01/01/2026', 'coluna_2': '31/12/2026'}
i = {'Dados Pessoais': 'Dados Pessoais'}
i = {'Dados Pessoais': 'CPF', 'coluna_1': '015.916.541-57', 'coluna_2': 'Matrícula Funcional', 'coluna_3': ''}
i = {'Dados Pessoais': 'Nome', 'coluna_1': 'ROSIMEIRE INACIO DE JESUS', 'coluna_2': 'Data de Nascimento', 'coluna_3': '29/09/1977'}
i = {'Dados Pessoais': 'Naturalidade', 'coluna_1': '', 'coluna_2': 'UF', 'coluna_3': ''}
i = {'Dados Pessoais': 'Nacionalidade', 'coluna_1': '', 'coluna_2': 'Sexo', 'coluna_3': 'Feminino'}
i = {'Dados Pessoais': 'Estado Civil', 'coluna_1': 'Não informado', 'coluna_2': 'Grau de Instrução', 'coluna_3': ''}
i = {'Dados Pessoais': 'Pai', 'coluna_1': '', 'coluna_2': '', 'coluna_3': ''}
i = {'Dados Pessoais': 'Mãe', 'coluna_1': 'MARIA GASPARINA DE JESUS', 'coluna_2': '', 'coluna_3': ''}
i = {'Endereço': 'Endereço'}
i = {'Endereço': 'Logradouro', 'coluna_1': ''}
i = {'Endereço': 'Bairro', 'coluna_1': '', 'coluna_2': 'Complemento', 'coluna_3': '', 'coluna_4': 'Cep', 'coluna_5': ''}
i = {'Endereço': 'Município', 'coluna_1': '', 'coluna_2': 'UF', 'coluna_3': '', 'coluna_4': '', 'coluna_5': ''}
i = {'Endereço': 'E-mail', 'coluna_1': '', 'coluna_2': 'Telefone', 'coluna_3': '', 'coluna_4': 'Tipo Moradia', 'coluna_5': ''}
i = {'Endereço': ''}
i = {'Endereço': 'Documento'}
i = {'Endereço': 'Identidade', 'coluna_1': '', 'coluna_2': 'Orgão Expedidor', 'coluna_3': '', 'coluna_4': 'Data Expedição', 'coluna_5': '', 'coluna_6': 'UF', 'coluna_7': ''}
i = {'Endereço': 'Título', 'coluna_1': '', 'coluna_2': 'Zona', 'coluna_3': '', 'coluna_4': 'Seção', 'coluna_5': '', 'coluna_6': 'UF', 'coluna_7': ''}
i = {'Endereço': 'C.Militar Número', 'coluna_1': '', 'coluna_2': 'C.M. Região', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Endereço': 'NCH Número', 'coluna_1': '', 'coluna_2': 'CNH Validade', 'coluna_3': '', 'coluna_4': 'CNH Dt. Exp', 'coluna_5': '', 'coluna_6': 'CNH Cart.', 'coluna_7': ''}
i = {'Endereço': 'IPASGO', 'coluna_1': '', 'coluna_2': 'PIS/PASEP', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Vínculos': 'Vínculos'}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '', 'coluna_1': '02/03/2026', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'C.Temporário - Apoio Administrativo - Nível Fundamental - SEDUC', 'coluna_1': '02/03/2026', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': 'EXECUTOR DE SERVIÇOS AUXILIARES', 'coluna_1': '02/03/2026', 'coluna_2': '31/12/2026'}
i = {'Dados Pessoais': 'Dados Pessoais'}
i = {'Dados Pessoais': 'CPF', 'coluna_1': '902.368.311-00', 'coluna_2': 'Matrícula Funcional', 'coluna_3': ''}
i = {'Dados Pessoais': 'Nome', 'coluna_1': 'SANDRO CARLOS DINIZ MENDES', 'coluna_2': 'Data de Nascimento', 'coluna_3': '20/08/1979'}
i = {'Dados Pessoais': 'Naturalidade', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO'}
i = {'Dados Pessoais': 'Nacionalidade', 'coluna_1': 'BRASIL', 'coluna_2': 'Sexo', 'coluna_3': 'Masculino'}
i = {'Dados Pessoais': 'Estado Civil', 'coluna_1': 'Casado(a)', 'coluna_2': 'Grau de Instrução', 'coluna_3': 'Educação Superior'}
i = {'Dados Pessoais': 'Pai', 'coluna_1': 'PAULO FERNANDO MENDES', 'coluna_2': '', 'coluna_3': ''}
i = {'Dados Pessoais': 'Mãe', 'coluna_1': 'MARIA DE FATIMA DINIZ MENDES', 'coluna_2': '', 'coluna_3': ''}
i = {'Endereço': 'Endereço'}
i = {'Endereço': 'Logradouro', 'coluna_1': 'RUA 37A QD 22 LT 37 APTO 303A'}
i = {'Endereço': 'Bairro', 'coluna_1': 'JARDIM BELA VISTA', 'coluna_2': 'Complemento', 'coluna_3': 'RESIDENCIAL VALENCIA', 'coluna_4': 'Cep', 'coluna_5': '74912-090'}
i = {'Endereço': 'Município', 'coluna_1': 'APARECIDA DE GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO', 'coluna_4': '', 'coluna_5': ''}
i = {'Endereço': 'E-mail', 'coluna_1': 'sandrocdm1@gmail.com', 'coluna_2': 'Telefone', 'coluna_3': '6232828395', 'coluna_4': 'Tipo Moradia', 'coluna_5': 'Própria'}
i = {'Endereço': ''}
i = {'Endereço': 'Documento'}
i = {'Endereço': 'Identidade', 'coluna_1': '3691308', 'coluna_2': 'Orgão Expedidor', 'coluna_3': 'SSP', 'coluna_4': 'Data Expedição', 'coluna_5': '17/10/1994', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'Título', 'coluna_1': '39015091015', 'coluna_2': 'Zona', 'coluna_3': '135', 'coluna_4': 'Seção', 'coluna_5': '169', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'C.Militar Número', 'coluna_1': '', 'coluna_2': 'C.M. Região', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Endereço': 'NCH Número', 'coluna_1': '', 'coluna_2': 'CNH Validade', 'coluna_3': '', 'coluna_4': 'CNH Dt. Exp', 'coluna_5': '', 'coluna_6': 'CNH Cart.', 'coluna_7': ''}
i = {'Endereço': 'IPASGO', 'coluna_1': '', 'coluna_2': 'PIS/PASEP', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Vínculos': 'Vínculos'}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '66600963', 'coluna_1': '18/10/2006', 'coluna_2': '31/12/2014'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'Professor III', 'coluna_1': '18/10/2006', 'coluna_2': '31/12/2014'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': '-', 'coluna_1': '-', 'coluna_2': '-'}
i = {'Vínculos': ''}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '', 'coluna_1': '01/11/2006', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'Professor IV', 'coluna_1': '01/11/2006', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': 'PROFESSOR DE 2ª FASE OU ENSINO MÉDIO', 'coluna_1': '01/01/2026', 'coluna_2': '31/12/2026'}
i = {'Vínculos': 'COORDENADOR DE ÁREA - CEPI', 'coluna_1': '01/01/2026', 'coluna_2': '31/12/2026'}
i = {'Dados Pessoais': 'Dados Pessoais'}
i = {'Dados Pessoais': 'CPF', 'coluna_1': '001.140.011-03', 'coluna_2': 'Matrícula Funcional', 'coluna_3': ''}
i = {'Dados Pessoais': 'Nome', 'coluna_1': 'SHEROLA PATRICIA MOREIRA PIMENTEL', 'coluna_2': 'Data de Nascimento', 'coluna_3': '05/01/1981'}
i = {'Dados Pessoais': 'Naturalidade', 'coluna_1': '', 'coluna_2': 'UF', 'coluna_3': ''}
i = {'Dados Pessoais': 'Nacionalidade', 'coluna_1': '', 'coluna_2': 'Sexo', 'coluna_3': 'Feminino'}
i = {'Dados Pessoais': 'Estado Civil', 'coluna_1': 'Não informado', 'coluna_2': 'Grau de Instrução', 'coluna_3': ''}
i = {'Dados Pessoais': 'Pai', 'coluna_1': '', 'coluna_2': '', 'coluna_3': ''}
i = {'Dados Pessoais': 'Mãe', 'coluna_1': 'SUELI PEREIRA DA SILVA MOREIRA', 'coluna_2': '', 'coluna_3': ''}
i = {'Endereço': 'Endereço'}
i = {'Endereço': 'Logradouro', 'coluna_1': ''}
i = {'Endereço': 'Bairro', 'coluna_1': '', 'coluna_2': 'Complemento', 'coluna_3': '', 'coluna_4': 'Cep', 'coluna_5': ''}
i = {'Endereço': 'Município', 'coluna_1': '', 'coluna_2': 'UF', 'coluna_3': '', 'coluna_4': '', 'coluna_5': ''}
i = {'Endereço': 'E-mail', 'coluna_1': '', 'coluna_2': 'Telefone', 'coluna_3': '', 'coluna_4': 'Tipo Moradia', 'coluna_5': ''}
i = {'Endereço': ''}
i = {'Endereço': 'Documento'}
i = {'Endereço': 'Identidade', 'coluna_1': '', 'coluna_2': 'Orgão Expedidor', 'coluna_3': '', 'coluna_4': 'Data Expedição', 'coluna_5': '', 'coluna_6': 'UF', 'coluna_7': ''}
i = {'Endereço': 'Título', 'coluna_1': '', 'coluna_2': 'Zona', 'coluna_3': '', 'coluna_4': 'Seção', 'coluna_5': '', 'coluna_6': 'UF', 'coluna_7': ''}
i = {'Endereço': 'C.Militar Número', 'coluna_1': '', 'coluna_2': 'C.M. Região', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Endereço': 'NCH Número', 'coluna_1': '', 'coluna_2': 'CNH Validade', 'coluna_3': '', 'coluna_4': 'CNH Dt. Exp', 'coluna_5': '', 'coluna_6': 'CNH Cart.', 'coluna_7': ''}
i = {'Endereço': 'IPASGO', 'coluna_1': '', 'coluna_2': 'PIS/PASEP', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Vínculos': 'Vínculos'}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '', 'coluna_1': '01/04/2025', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'C.Temporário - Apoio Administrativo - Nível Fundamental - SEDUC', 'coluna_1': '01/04/2025', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': 'MERENDEIRA', 'coluna_1': '30/01/2026', 'coluna_2': '31/12/2026'}
i = {'Dados Pessoais': 'Dados Pessoais'}
i = {'Dados Pessoais': 'CPF', 'coluna_1': '704.746.481-68', 'coluna_2': 'Matrícula Funcional', 'coluna_3': ''}
i = {'Dados Pessoais': 'Nome', 'coluna_1': 'TAMERA NUNES VIEIRA ALMEIDA', 'coluna_2': 'Data de Nascimento', 'coluna_3': '19/11/1982'}
i = {'Dados Pessoais': 'Naturalidade', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO'}
i = {'Dados Pessoais': 'Nacionalidade', 'coluna_1': 'BRASIL', 'coluna_2': 'Sexo', 'coluna_3': 'Feminino'}
i = {'Dados Pessoais': 'Estado Civil', 'coluna_1': 'Casado(a)', 'coluna_2': 'Grau de Instrução', 'coluna_3': 'Educação Superior'}
i = {'Dados Pessoais': 'Pai', 'coluna_1': 'LAUZANIO GOMES VIEIRA', 'coluna_2': '', 'coluna_3': ''}
i = {'Dados Pessoais': 'Mãe', 'coluna_1': 'GISELVA DO ROSARIO NUNES VIEIRA', 'coluna_2': '', 'coluna_3': ''}
i = {'Endereço': 'Endereço'}
i = {'Endereço': 'Logradouro', 'coluna_1': 'RUA AR4'}
i = {'Endereço': 'Bairro', 'coluna_1': 'ARUANA II', 'coluna_2': 'Complemento', 'coluna_3': 'QD 10 LT 07', 'coluna_4': 'Cep', 'coluna_5': '74740-310'}
i = {'Endereço': 'Município', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO', 'coluna_4': '', 'coluna_5': ''}
i = {'Endereço': 'E-mail', 'coluna_1': 'tamaraalmeida@hotmail.com', 'coluna_2': 'Telefone', 'coluna_3': '6285547317', 'coluna_4': 'Tipo Moradia', 'coluna_5': 'Própria'}
i = {'Endereço': ''}
i = {'Endereço': 'Documento'}
i = {'Endereço': 'Identidade', 'coluna_1': '4195313', 'coluna_2': 'Orgão Expedidor', 'coluna_3': 'SSP', 'coluna_4': 'Data Expedição', 'coluna_5': '20/02/2002', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'Título', 'coluna_1': '048548471023', 'coluna_2': 'Zona', 'coluna_3': '135', 'coluna_4': 'Seção', 'coluna_5': '273', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'C.Militar Número', 'coluna_1': '', 'coluna_2': 'C.M. Região', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Endereço': 'NCH Número', 'coluna_1': '', 'coluna_2': 'CNH Validade', 'coluna_3': '', 'coluna_4': 'CNH Dt. Exp', 'coluna_5': '', 'coluna_6': 'CNH Cart.', 'coluna_7': ''}
i = {'Endereço': 'IPASGO', 'coluna_1': '', 'coluna_2': 'PIS/PASEP', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Vínculos': 'Vínculos'}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '66230852', 'coluna_1': '17/12/2010', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'Professor III', 'coluna_1': '17/12/2010', 'coluna_2': '31/12/2020'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': '-', 'coluna_1': '-', 'coluna_2': '-'}
i = {'Vínculos': 'Professor IV', 'coluna_1': '17/12/2010', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': 'COORDENADOR ADMINISTRATIVO FINANCEIRO', 'coluna_1': '01/01/2026', 'coluna_2': '31/12/2026'}
i = {'Dados Pessoais': 'Dados Pessoais'}
i = {'Dados Pessoais': 'CPF', 'coluna_1': '166.358.411-72', 'coluna_2': 'Matrícula Funcional', 'coluna_3': ''}
i = {'Dados Pessoais': 'Nome', 'coluna_1': 'VALDELY CARDOSO DE OLIVEIRA', 'coluna_2': 'Data de Nascimento', 'coluna_3': '28/12/1957'}
i = {'Dados Pessoais': 'Naturalidade', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO'}
i = {'Dados Pessoais': 'Nacionalidade', 'coluna_1': 'BRASIL', 'coluna_2': 'Sexo', 'coluna_3': 'Masculino'}
i = {'Dados Pessoais': 'Estado Civil', 'coluna_1': 'Solteiro(a)', 'coluna_2': 'Grau de Instrução', 'coluna_3': 'Ensino Médio'}
i = {'Dados Pessoais': 'Pai', 'coluna_1': 'DIORCINIO ALVES DE OLIVEIRA', 'coluna_2': '', 'coluna_3': ''}
i = {'Dados Pessoais': 'Mãe', 'coluna_1': 'ERMELINDA CARDOSO OLIVEIRA', 'coluna_2': '', 'coluna_3': ''}
i = {'Endereço': 'Endereço'}
i = {'Endereço': 'Logradouro', 'coluna_1': 'RUA 217'}
i = {'Endereço': 'Bairro', 'coluna_1': 'UNIVERSITARIO', 'coluna_2': 'Complemento', 'coluna_3': '', 'coluna_4': 'Cep', 'coluna_5': '74000-000'}
i = {'Endereço': 'Município', 'coluna_1': '', 'coluna_2': 'UF', 'coluna_3': '', 'coluna_4': '', 'coluna_5': ''}
i = {'Endereço': 'E-mail', 'coluna_1': '', 'coluna_2': 'Telefone', 'coluna_3': '', 'coluna_4': 'Tipo Moradia', 'coluna_5': 'Própria'}
i = {'Endereço': ''}
i = {'Endereço': 'Documento'}
i = {'Endereço': 'Identidade', 'coluna_1': '811996', 'coluna_2': 'Orgão Expedidor', 'coluna_3': 'SSP', 'coluna_4': 'Data Expedição', 'coluna_5': '28/12/1957', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'Título', 'coluna_1': '020341081031', 'coluna_2': 'Zona', 'coluna_3': '136', 'coluna_4': 'Seção', 'coluna_5': '197', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'C.Militar Número', 'coluna_1': '', 'coluna_2': 'C.M. Região', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Endereço': 'NCH Número', 'coluna_1': '', 'coluna_2': 'CNH Validade', 'coluna_3': '', 'coluna_4': 'CNH Dt. Exp', 'coluna_5': '', 'coluna_6': 'CNH Cart.', 'coluna_7': ''}
i = {'Endereço': 'IPASGO', 'coluna_1': '', 'coluna_2': 'PIS/PASEP', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Vínculos': 'Vínculos'}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '', 'coluna_1': '04/12/2023', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'C.Temporário - Apoio Administrativo - Nível Fundamental - SEDUC', 'coluna_1': '04/12/2023', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': 'VIGIA', 'coluna_1': '01/01/2026', 'coluna_2': '31/12/2026'}
i = {'Dados Pessoais': 'Dados Pessoais'}
i = {'Dados Pessoais': 'CPF', 'coluna_1': '664.249.841-00', 'coluna_2': 'Matrícula Funcional', 'coluna_3': ''}
i = {'Dados Pessoais': 'Nome', 'coluna_1': 'VALDETE DE REZENDE LOPES', 'coluna_2': 'Data de Nascimento', 'coluna_3': '08/07/1972'}
i = {'Dados Pessoais': 'Naturalidade', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO'}
i = {'Dados Pessoais': 'Nacionalidade', 'coluna_1': 'BRASIL', 'coluna_2': 'Sexo', 'coluna_3': 'Feminino'}
i = {'Dados Pessoais': 'Estado Civil', 'coluna_1': 'Casado(a)', 'coluna_2': 'Grau de Instrução', 'coluna_3': 'Educação Superior'}
i = {'Dados Pessoais': 'Pai', 'coluna_1': 'JOSUÉ VELOSO DE REZENDE', 'coluna_2': '', 'coluna_3': ''}
i = {'Dados Pessoais': 'Mãe', 'coluna_1': 'LOURDES ETERNA DE JESUS', 'coluna_2': '', 'coluna_3': ''}
i = {'Endereço': 'Endereço'}
i = {'Endereço': 'Logradouro', 'coluna_1': 'RUA F2'}
i = {'Endereço': 'Bairro', 'coluna_1': 'JD CALIFÓRNIA', 'coluna_2': 'Complemento', 'coluna_3': 'Q 2, L 01 CONJ. ARUANA 1', 'coluna_4': 'Cep', 'coluna_5': '74740-100'}
i = {'Endereço': 'Município', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO', 'coluna_4': '', 'coluna_5': ''}
i = {'Endereço': 'E-mail', 'coluna_1': 'VALDETEDEREZENDELOPES@GMAIL.COM', 'coluna_2': 'Telefone', 'coluna_3': '6232842449', 'coluna_4': 'Tipo Moradia', 'coluna_5': 'Própria'}
i = {'Endereço': ''}
i = {'Endereço': 'Documento'}
i = {'Endereço': 'Identidade', 'coluna_1': '2887325', 'coluna_2': 'Orgão Expedidor', 'coluna_3': 'SSP', 'coluna_4': 'Data Expedição', 'coluna_5': '10/11/1988', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'Título', 'coluna_1': '27479781015', 'coluna_2': 'Zona', 'coluna_3': '84', 'coluna_4': 'Seção', 'coluna_5': '2', 'coluna_6': 'UF', 'coluna_7': 'GO'}
i = {'Endereço': 'C.Militar Número', 'coluna_1': '', 'coluna_2': 'C.M. Região', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Endereço': 'NCH Número', 'coluna_1': '', 'coluna_2': 'CNH Validade', 'coluna_3': '', 'coluna_4': 'CNH Dt. Exp', 'coluna_5': '', 'coluna_6': 'CNH Cart.', 'coluna_7': ''}
i = {'Endereço': 'IPASGO', 'coluna_1': '', 'coluna_2': 'PIS/PASEP', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Vínculos': 'Vínculos'}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '65002851', 'coluna_1': '15/08/1999', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'Professor III', 'coluna_1': '15/08/1999', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': '-', 'coluna_1': '-', 'coluna_2': '-'}
i = {'Vínculos': 'Professor IV', 'coluna_1': '15/08/1999', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': 'PROFESSOR DE 2ª FASE OU ENSINO MÉDIO', 'coluna_1': '01/01/2026', 'coluna_2': '31/12/2026'}
i = {'Dados Pessoais': 'Dados Pessoais'}
i = {'Dados Pessoais': 'CPF', 'coluna_1': '287.540.341-91', 'coluna_2': 'Matrícula Funcional', 'coluna_3': ''}
i = {'Dados Pessoais': 'Nome', 'coluna_1': 'ZILMA BARBOSA LIMA MORAIS', 'coluna_2': 'Data de Nascimento', 'coluna_3': '02/06/1963'}
i = {'Dados Pessoais': 'Naturalidade', 'coluna_1': 'GOIATINS', 'coluna_2': 'UF', 'coluna_3': 'TO'}
i = {'Dados Pessoais': 'Nacionalidade', 'coluna_1': 'BRASIL', 'coluna_2': 'Sexo', 'coluna_3': 'Feminino'}
i = {'Dados Pessoais': 'Estado Civil', 'coluna_1': 'Casado(a)', 'coluna_2': 'Grau de Instrução', 'coluna_3': 'Educação Superior'}
i = {'Dados Pessoais': 'Pai', 'coluna_1': 'SINEZIO ALVES LIMA', 'coluna_2': '', 'coluna_3': ''}
i = {'Dados Pessoais': 'Mãe', 'coluna_1': 'TEREZA BARBOSA LIMA', 'coluna_2': '', 'coluna_3': ''}
i = {'Endereço': 'Endereço'}
i = {'Endereço': 'Logradouro', 'coluna_1': 'RUA PERIMENTRAL 5'}
i = {'Endereço': 'Bairro', 'coluna_1': 'ARUANÃ I', 'coluna_2': 'Complemento', 'coluna_3': 'QD. 06 LT.07', 'coluna_4': 'Cep', 'coluna_5': '74740-240'}
i = {'Endereço': 'Município', 'coluna_1': 'GOIÂNIA', 'coluna_2': 'UF', 'coluna_3': 'GO', 'coluna_4': '', 'coluna_5': ''}
i = {'Endereço': 'E-mail', 'coluna_1': 'zilma_blm@yahoo.com.br', 'coluna_2': 'Telefone', 'coluna_3': '62982059809', 'coluna_4': 'Tipo Moradia', 'coluna_5': 'Própria'}
i = {'Endereço': ''}
i = {'Endereço': 'Documento'}
i = {'Endereço': 'Identidade', 'coluna_1': '1425805', 'coluna_2': 'Orgão Expedidor', 'coluna_3': 'SSP', 'coluna_4': 'Data Expedição', 'coluna_5': '20/12/1990', 'coluna_6': 'UF', 'coluna_7': 'DF'}
i = {'Endereço': 'Título', 'coluna_1': '14297052011', 'coluna_2': 'Zona', 'coluna_3': '012', 'coluna_4': 'Seção', 'coluna_5': '0029', 'coluna_6': 'UF', 'coluna_7': 'DF'}
i = {'Endereço': 'C.Militar Número', 'coluna_1': '', 'coluna_2': 'C.M. Região', 'coluna_3': '', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Endereço': 'NCH Número', 'coluna_1': '02068922618', 'coluna_2': 'CNH Validade', 'coluna_3': '01/08/2016', 'coluna_4': 'CNH Dt. Exp', 'coluna_5': '26/11/1991', 'coluna_6': 'CNH Cart.', 'coluna_7': 'B'}
i = {'Endereço': 'IPASGO', 'coluna_1': '', 'coluna_2': 'PIS/PASEP', 'coluna_3': '12064310799', 'coluna_4': '', 'coluna_5': '', 'coluna_6': '', 'coluna_7': ''}
i = {'Vínculos': 'Vínculos'}
i = {'Vínculos': 'Matrícula Holerite', 'coluna_1': 'Data Início', 'coluna_2': 'Data Término'}
i = {'Vínculos': '', 'coluna_1': '01/08/2007', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Cargo(s)'}
i = {'Vínculos': 'Professor III', 'coluna_1': '01/08/2007', 'coluna_2': '23/09/2014'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': '-', 'coluna_1': '-', 'coluna_2': '-'}
i = {'Vínculos': 'Professor IV', 'coluna_1': '01/08/2007', 'coluna_2': 'Ativo'}
i = {'Vínculos': 'Funções'}
i = {'Vínculos': 'PROFESSOR DE 2ª FASE OU ENSINO MÉDIO', 'coluna_1': '01/01/2026', 'coluna_2': '31/12/2026'}
