from typing import Any


class TipagemNavegação:
    def clicar(self, *args, **kwargs) -> None: ...
    def caminhar(self, *args, **kwargs) -> None: ...
    def acessar_página(self, *args, **kwargs) -> None: ...
    def digitar_xpath(self, *args, **kwargs) -> None: ...
    def obter_elemento(self, *args, **kwargs) -> Any: ...
    def aguardar_página(self, *args, **kwargs) -> None: ...
    def aguardar_preenchimento(self, *args, **kwargs) -> None: ...
    def selecionar_dropdown(self, *args, **kwargs) -> None: ...
    def obter_turmas_siap(self, *args, **kwargs) -> Any: ...
    def iterar_turmas(self, *args, **kwargs) -> Any: ...
